// Code generated by ddbgen. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"iter"
	"strconv"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// paymentPK encodes the Payment pk ("TENANT#{TenantID}") attribute.
func paymentPK(tenantID string) (string, error) {
	s0, err := runtime.CheckSegment(tenantID)
	if err != nil {
		return "", fmt.Errorf("Payment pk {TenantID}: %w", err)
	}
	return "TENANT#" + s0, nil
}

// paymentSK encodes the Payment sk ("PAY#{OrderID}#{PaymentID}") attribute.
func paymentSK(orderID string, paymentID string) (string, error) {
	s0, err := runtime.CheckSegment(orderID)
	if err != nil {
		return "", fmt.Errorf("Payment sk {OrderID}: %w", err)
	}
	s1, err := runtime.CheckSegment(paymentID)
	if err != nil {
		return "", fmt.Errorf("Payment sk {PaymentID}: %w", err)
	}
	return "PAY#" + s0 + "#" + s1, nil
}

// PaymentKey identifies one Payment by its key source fields.
type PaymentKey struct {
	TenantID  string
	OrderID   string
	PaymentID string
}

func (Payment) isAppItem() {}

// marshalPayment marshals p and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalPayment(p *Payment) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(p)
	if err != nil {
		return nil, fmt.Errorf("marshaling Payment: %w", err)
	}
	pk, err := paymentPK(p.TenantID)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := paymentSK(p.OrderID, p.PaymentID)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "payment"}
	return av, nil
}

func unmarshalPayment(av map[string]types.AttributeValue) (*Payment, error) {
	var p Payment
	if err := attributevalue.UnmarshalMap(av, &p); err != nil {
		return nil, fmt.Errorf("unmarshaling Payment: %w", err)
	}
	return &p, nil
}

// GetPayment loads the Payment identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *AppClient) GetPayment(ctx context.Context, tenantID string, orderID string, paymentID string, opts ...runtime.ReadOpt) (*Payment, error) {
	pk, err := paymentPK(tenantID)
	if err != nil {
		return nil, err
	}
	sk, err := paymentSK(orderID, paymentID)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetPayment: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetPayment: %w", runtime.ErrNotFound)
	}
	return unmarshalPayment(out.Item)
}

// PutPayment writes p unconditionally (last writer wins).
func (c *AppClient) PutPayment(ctx context.Context, p *Payment) error {
	av, err := marshalPayment(p)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutPayment: %w", err)
	}
	return nil
}

// PutPaymentIfNotExists writes p only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *AppClient) PutPaymentIfNotExists(ctx context.Context, p *Payment) error {
	av, err := marshalPayment(p)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutPaymentIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutPaymentIfNotExists: %w", err)
	}
	return nil
}

// DeletePayment deletes the Payment identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *AppClient) DeletePayment(ctx context.Context, tenantID string, orderID string, paymentID string, opts ...runtime.DeleteOpt) error {
	pk, err := paymentPK(tenantID)
	if err != nil {
		return err
	}
	sk, err := paymentSK(orderID, paymentID)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeletePayment: Payment declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeletePayment: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeletePayment: %w", err)
	}
	return nil
}

// PaymentUpdate is a typed update builder for Payment. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type PaymentUpdate struct {
	c    *AppClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdatePayment starts a typed update of the Payment identified by
// the given key fields.
func (c *AppClient) UpdatePayment(tenantID string, orderID string, paymentID string) *PaymentUpdate {
	u := &PaymentUpdate{c: c}
	pk, err := paymentPK(tenantID)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := paymentSK(orderID, paymentID)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// SetAmountCts sets the AmountCts attribute.
func (u *PaymentUpdate) SetAmountCts(amountCts int64) *PaymentUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(amountCts)
	if err != nil {
		u.err = fmt.Errorf("SetAmountCts: %w", err)
		return u
	}
	u.expr.Set("amount_cts", av)
	return u
}

// AddAmountCts atomically adds delta to the AmountCts attribute.
func (u *PaymentUpdate) AddAmountCts(delta int64) *PaymentUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Add("amount_cts", &types.AttributeValueMemberN{Value: strconv.FormatInt(delta, 10)})
	return u
}

// RemoveAmountCts removes the AmountCts attribute from the item.
func (u *PaymentUpdate) RemoveAmountCts() *PaymentUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("amount_cts")
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Payment. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *PaymentUpdate) Run(ctx context.Context) (*Payment, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("PaymentUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("PaymentUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("PaymentUpdate: %w", err)
	}
	return unmarshalPayment(out.Attributes)
}

// PaymentsByOrderQuery is the chainable builder for the PaymentsByOrder access
// pattern. Terminate with All or Page.
type PaymentsByOrderQuery struct {
	c          *AppClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// PaymentsByOrder queries pk = "TENANT#{TenantID}", sk begins "PAY#{OrderID}#" on the main index.
func (c *AppClient) PaymentsByOrder(tenantID string, orderID string) *PaymentsByOrderQuery {
	q := &PaymentsByOrderQuery{c: c}
	pk, err := paymentPK(tenantID)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.CheckSegment(orderID)
	if err != nil {
		q.err = fmt.Errorf("Payment sk condition {OrderID}: %w", err)
		return q
	}
	q.skPrefix = "PAY#" + cs0 + "#"
	q.cond = runtime.SKBegins(q.skPrefix)
	return q
}

// Desc returns results in descending key order.
func (q *PaymentsByOrderQuery) Desc() *PaymentsByOrderQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *PaymentsByOrderQuery) Limit(n int32) *PaymentsByOrderQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *PaymentsByOrderQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *PaymentsByOrderQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *PaymentsByOrderQuery) ConsistentRead() *PaymentsByOrderQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *PaymentsByOrderQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "payment",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Payment, paginating
// internally. Iteration stops after yielding the first error.
func (q *PaymentsByOrderQuery) All(ctx context.Context) iter.Seq2[Payment, error] {
	if q.err != nil {
		return func(yield func(Payment, error) bool) {
			var zero Payment
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalPayment)
}

// Page returns one page of matching Payment items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *PaymentsByOrderQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Payment, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalPayment)
}

// BatchGetPayments loads Payments by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *AppClient) BatchGetPayments(ctx context.Context, keys []PaymentKey, opts ...runtime.ReadOpt) ([]Payment, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := paymentPK(k.TenantID)
		if err != nil {
			return nil, err
		}
		sk, err := paymentSK(k.OrderID, k.PaymentID)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Payment, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalPayment(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutPayments writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *AppClient) BatchPutPayments(ctx context.Context, items []Payment) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalPayment(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutPayment returns a TransactWriteItem putting p (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *AppClient) TransactPutPayment(p *Payment) (types.TransactWriteItem, error) {
	av, err := marshalPayment(p)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeletePayment returns a TransactWriteItem deleting the
// Payment identified by the given key fields.
func (c *AppClient) TransactDeletePayment(tenantID string, orderID string, paymentID string) (types.TransactWriteItem, error) {
	pk, err := paymentPK(tenantID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := paymentSK(orderID, paymentID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
