// Code generated by ddbgen. DO NOT EDIT.

package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// tenantPK encodes the Tenant pk ("TENANT#{TenantID}") attribute.
func tenantPK(tenantID string) (string, error) {
	s0, err := runtime.CheckSegment(tenantID)
	if err != nil {
		return "", fmt.Errorf("Tenant pk {TenantID}: %w", err)
	}
	return "TENANT#" + s0, nil
}

// tenantSK encodes the Tenant sk ("TENANT#{TenantID}") attribute.
func tenantSK(tenantID string) (string, error) {
	s0, err := runtime.CheckSegment(tenantID)
	if err != nil {
		return "", fmt.Errorf("Tenant sk {TenantID}: %w", err)
	}
	return "TENANT#" + s0, nil
}

// TenantKey identifies one Tenant by its key source fields.
type TenantKey struct {
	TenantID string
}

func (Tenant) isAppItem() {}

// marshalTenant marshals t and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalTenant(t *Tenant) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(t)
	if err != nil {
		return nil, fmt.Errorf("marshaling Tenant: %w", err)
	}
	pk, err := tenantPK(t.TenantID)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := tenantSK(t.TenantID)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "tenant"}
	return av, nil
}

func unmarshalTenant(av map[string]types.AttributeValue) (*Tenant, error) {
	var t Tenant
	if err := attributevalue.UnmarshalMap(av, &t); err != nil {
		return nil, fmt.Errorf("unmarshaling Tenant: %w", err)
	}
	return &t, nil
}

// GetTenant loads the Tenant identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists.
func (c *AppClient) GetTenant(ctx context.Context, tenantID string) (*Tenant, error) {
	pk, err := tenantPK(tenantID)
	if err != nil {
		return nil, err
	}
	sk, err := tenantSK(tenantID)
	if err != nil {
		return nil, err
	}
	out, err := c.ddb.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("GetTenant: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetTenant: %w", runtime.ErrNotFound)
	}
	return unmarshalTenant(out.Item)
}

// PutTenant writes t unconditionally (last writer wins).
func (c *AppClient) PutTenant(ctx context.Context, t *Tenant) error {
	av, err := marshalTenant(t)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutTenant: %w", err)
	}
	return nil
}

// PutTenantIfNotExists writes t only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *AppClient) PutTenantIfNotExists(ctx context.Context, t *Tenant) error {
	av, err := marshalTenant(t)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutTenantIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutTenantIfNotExists: %w", err)
	}
	return nil
}

// DeleteTenant deletes the Tenant identified by the given key
// fields. Deleting a missing item is not an error.
func (c *AppClient) DeleteTenant(ctx context.Context, tenantID string) error {
	pk, err := tenantPK(tenantID)
	if err != nil {
		return err
	}
	sk, err := tenantSK(tenantID)
	if err != nil {
		return err
	}
	if _, err := c.ddb.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}); err != nil {
		return fmt.Errorf("DeleteTenant: %w", err)
	}
	return nil
}

// TenantUpdate is a typed update builder for Tenant. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type TenantUpdate struct {
	c    *AppClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateTenant starts a typed update of the Tenant identified by
// the given key fields.
func (c *AppClient) UpdateTenant(tenantID string) *TenantUpdate {
	u := &TenantUpdate{c: c}
	pk, err := tenantPK(tenantID)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := tenantSK(tenantID)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// SetName sets the Name attribute.
func (u *TenantUpdate) SetName(name string) *TenantUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(name)
	if err != nil {
		u.err = fmt.Errorf("SetName: %w", err)
		return u
	}
	u.expr.Set("name", av)
	return u
}

// RemoveName removes the Name attribute from the item.
func (u *TenantUpdate) RemoveName() *TenantUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("name")
	return u
}

// SetPlan sets the Plan attribute.
func (u *TenantUpdate) SetPlan(plan string) *TenantUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(plan)
	if err != nil {
		u.err = fmt.Errorf("SetPlan: %w", err)
		return u
	}
	u.expr.Set("plan", av)
	return u
}

// RemovePlan removes the Plan attribute from the item.
func (u *TenantUpdate) RemovePlan() *TenantUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("plan")
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Tenant. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *TenantUpdate) Run(ctx context.Context) (*Tenant, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("TenantUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("TenantUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("TenantUpdate: %w", err)
	}
	return unmarshalTenant(out.Attributes)
}

// BatchGetTenants loads Tenants by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Missing keys are
// omitted from the result. On exhausted retries the fetched subset is
// returned along with runtime.ErrUnprocessedRemain.
func (c *AppClient) BatchGetTenants(ctx context.Context, keys []TenantKey) ([]Tenant, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := tenantPK(k.TenantID)
		if err != nil {
			return nil, err
		}
		sk, err := tenantSK(k.TenantID)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk)
	out := make([]Tenant, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalTenant(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutTenants writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff.
func (c *AppClient) BatchPutTenants(ctx context.Context, items []Tenant) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalTenant(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutTenant returns a TransactWriteItem putting t (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *AppClient) TransactPutTenant(t *Tenant) (types.TransactWriteItem, error) {
	av, err := marshalTenant(t)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteTenant returns a TransactWriteItem deleting the
// Tenant identified by the given key fields.
func (c *AppClient) TransactDeleteTenant(tenantID string) (types.TransactWriteItem, error) {
	pk, err := tenantPK(tenantID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := tenantSK(tenantID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
