// Code generated by ddbgen. DO NOT EDIT.

package encoders

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// escapedPK encodes the Escaped pk ("E#{Raw:urlenc}") attribute.
func escapedPK(rawArg string) (string, error) {
	s0, err := runtime.CheckSegment(runtime.EncodeURL(rawArg))
	if err != nil {
		return "", fmt.Errorf("Escaped pk {Raw:urlenc}: %w", err)
	}
	return "E#" + s0, nil
}

// escapedSK encodes the Escaped sk ("B#{Blob:hex}") attribute.
func escapedSK(blob []byte) (string, error) {
	s0, err := runtime.CheckSegment(runtime.EncodeHex(blob))
	if err != nil {
		return "", fmt.Errorf("Escaped sk {Blob:hex}: %w", err)
	}
	return "B#" + s0, nil
}

// EscapedKey identifies one Escaped by its key source fields.
type EscapedKey struct {
	Raw  string
	Blob []byte
}

func (Escaped) isEncItem() {}

// marshalEscaped marshals e and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalEscaped(e *Escaped) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(e)
	if err != nil {
		return nil, fmt.Errorf("marshaling Escaped: %w", err)
	}
	pk, err := escapedPK(e.Raw)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := escapedSK(e.Blob)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "escaped"}
	return av, nil
}

func unmarshalEscaped(av map[string]types.AttributeValue) (*Escaped, error) {
	var e Escaped
	if err := attributevalue.UnmarshalMap(av, &e); err != nil {
		return nil, fmt.Errorf("unmarshaling Escaped: %w", err)
	}
	return &e, nil
}

// GetEscaped loads the Escaped identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *EncClient) GetEscaped(ctx context.Context, rawArg string, blob []byte, opts ...runtime.ReadOpt) (*Escaped, error) {
	pk, err := escapedPK(rawArg)
	if err != nil {
		return nil, err
	}
	sk, err := escapedSK(blob)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetEscaped: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetEscaped: %w", runtime.ErrNotFound)
	}
	return unmarshalEscaped(out.Item)
}

// PutEscaped writes e unconditionally (last writer wins).
func (c *EncClient) PutEscaped(ctx context.Context, e *Escaped) error {
	av, err := marshalEscaped(e)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutEscaped: %w", err)
	}
	return nil
}

// PutEscapedIfNotExists writes e only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *EncClient) PutEscapedIfNotExists(ctx context.Context, e *Escaped) error {
	av, err := marshalEscaped(e)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutEscapedIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutEscapedIfNotExists: %w", err)
	}
	return nil
}

// DeleteEscaped deletes the Escaped identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *EncClient) DeleteEscaped(ctx context.Context, rawArg string, blob []byte, opts ...runtime.DeleteOpt) error {
	pk, err := escapedPK(rawArg)
	if err != nil {
		return err
	}
	sk, err := escapedSK(blob)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteEscaped: Escaped declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteEscaped: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteEscaped: %w", err)
	}
	return nil
}

// EscapedUpdate is a typed update builder for Escaped. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type EscapedUpdate struct {
	c    *EncClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateEscaped starts a typed update of the Escaped identified by
// the given key fields.
func (c *EncClient) UpdateEscaped(rawArg string, blob []byte) *EscapedUpdate {
	u := &EscapedUpdate{c: c}
	pk, err := escapedPK(rawArg)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := escapedSK(blob)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Escaped. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *EscapedUpdate) Run(ctx context.Context) (*Escaped, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("EscapedUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("EscapedUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("EscapedUpdate: %w", err)
	}
	return unmarshalEscaped(out.Attributes)
}

// BatchGetEscapeds loads Escapeds by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *EncClient) BatchGetEscapeds(ctx context.Context, keys []EscapedKey, opts ...runtime.ReadOpt) ([]Escaped, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := escapedPK(k.Raw)
		if err != nil {
			return nil, err
		}
		sk, err := escapedSK(k.Blob)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Escaped, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalEscaped(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutEscapeds writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *EncClient) BatchPutEscapeds(ctx context.Context, items []Escaped) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalEscaped(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutEscaped returns a TransactWriteItem putting e (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *EncClient) TransactPutEscaped(e *Escaped) (types.TransactWriteItem, error) {
	av, err := marshalEscaped(e)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteEscaped returns a TransactWriteItem deleting the
// Escaped identified by the given key fields.
func (c *EncClient) TransactDeleteEscaped(rawArg string, blob []byte) (types.TransactWriteItem, error) {
	pk, err := escapedPK(rawArg)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := escapedSK(blob)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
