// Code generated by ddbgen. DO NOT EDIT.

package encoders

import (
	"context"
	"fmt"
	"iter"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// samplePK encodes the Sample pk ("S#{ID:ulid}") attribute.
func samplePK(id string) (string, error) {
	s0, err := runtime.EncodeULID(id)
	if err != nil {
		return "", fmt.Errorf("Sample pk {ID:ulid}: %w", err)
	}
	return "S#" + s0, nil
}

// sampleSK encodes the Sample sk ("V#{Ver2:pad6}#{Sum:hex}") attribute.
func sampleSK(ver2 uint32, sum [8]byte) (string, error) {
	s0, err := runtime.EncodePadUint(uint64(ver2), 6)
	if err != nil {
		return "", fmt.Errorf("Sample sk {Ver2:pad6}: %w", err)
	}
	s1 := runtime.EncodeHex(sum[:])
	return "V#" + s0 + "#" + s1, nil
}

// sampleBYSTAMPPK encodes the Sample bystamppk ("D#{Digest:hex}") attribute.
func sampleBYSTAMPPK(digest [16]byte) (string, error) {
	s0 := runtime.EncodeHex(digest[:])
	return "D#" + s0, nil
}

// sampleBYSTAMPSK encodes the Sample bystampsk ("{StampMS:epochms}") attribute.
func sampleBYSTAMPSK(stampMS int64) (string, error) {
	s0, err := runtime.EncodeEpochMS(stampMS)
	if err != nil {
		return "", fmt.Errorf("Sample bystampsk {StampMS:epochms}: %w", err)
	}
	return s0, nil
}

// SampleKey identifies one Sample by its key source fields.
type SampleKey struct {
	ID   string
	Ver2 uint32
	Sum  [8]byte
}

func (Sample) isEncItem() {}

// marshalSample marshals it and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalSample(it *Sample) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(it)
	if err != nil {
		return nil, fmt.Errorf("marshaling Sample: %w", err)
	}
	pk, err := samplePK(it.ID)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := sampleSK(it.Ver2, it.Sum)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	bystamppk, err := sampleBYSTAMPPK(it.Digest)
	if err != nil {
		return nil, err
	}
	av["bystamppk"] = &types.AttributeValueMemberS{Value: bystamppk}
	bystampsk, err := sampleBYSTAMPSK(it.StampMS)
	if err != nil {
		return nil, err
	}
	av["bystampsk"] = &types.AttributeValueMemberS{Value: bystampsk}
	av["_et"] = &types.AttributeValueMemberS{Value: "sample"}
	return av, nil
}

func unmarshalSample(av map[string]types.AttributeValue) (*Sample, error) {
	var it Sample
	if err := attributevalue.UnmarshalMap(av, &it); err != nil {
		return nil, fmt.Errorf("unmarshaling Sample: %w", err)
	}
	return &it, nil
}

// GetSample loads the Sample identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *EncClient) GetSample(ctx context.Context, id string, ver2 uint32, sum [8]byte, opts ...runtime.ReadOpt) (*Sample, error) {
	pk, err := samplePK(id)
	if err != nil {
		return nil, err
	}
	sk, err := sampleSK(ver2, sum)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetSample: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetSample: %w", runtime.ErrNotFound)
	}
	return unmarshalSample(out.Item)
}

// PutSample writes it unconditionally (last writer wins).
func (c *EncClient) PutSample(ctx context.Context, it *Sample) error {
	av, err := marshalSample(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutSample: %w", err)
	}
	return nil
}

// PutSampleIfNotExists writes it only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *EncClient) PutSampleIfNotExists(ctx context.Context, it *Sample) error {
	av, err := marshalSample(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutSampleIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutSampleIfNotExists: %w", err)
	}
	return nil
}

// DeleteSample deletes the Sample identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *EncClient) DeleteSample(ctx context.Context, id string, ver2 uint32, sum [8]byte, opts ...runtime.DeleteOpt) error {
	pk, err := samplePK(id)
	if err != nil {
		return err
	}
	sk, err := sampleSK(ver2, sum)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteSample: Sample declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteSample: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteSample: %w", err)
	}
	return nil
}

// SampleUpdate is a typed update builder for Sample. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type SampleUpdate struct {
	c    *EncClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateSample starts a typed update of the Sample identified by
// the given key fields.
func (c *EncClient) UpdateSample(id string, ver2 uint32, sum [8]byte) *SampleUpdate {
	u := &SampleUpdate{c: c}
	pk, err := samplePK(id)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := sampleSK(ver2, sum)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// SetDigest sets the Digest attribute and recomputes the
// synthesized bystamppk key attribute (ByStamp stays in sync).
func (u *SampleUpdate) SetDigest(digest [16]byte) *SampleUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(digest)
	if err != nil {
		u.err = fmt.Errorf("SetDigest: %w", err)
		return u
	}
	u.expr.Set("digest", av)
	bystamppk, err := sampleBYSTAMPPK(digest)
	if err != nil {
		u.err = fmt.Errorf("SetDigest: %w", err)
		return u
	}
	u.expr.Set("bystamppk", &types.AttributeValueMemberS{Value: bystamppk})
	return u
}

// SetStampMS sets the StampMS attribute and recomputes the
// synthesized bystampsk key attribute (ByStamp stays in sync).
func (u *SampleUpdate) SetStampMS(stampMS int64) *SampleUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(stampMS)
	if err != nil {
		u.err = fmt.Errorf("SetStampMS: %w", err)
		return u
	}
	u.expr.Set("stamp_ms", av)
	bystampsk, err := sampleBYSTAMPSK(stampMS)
	if err != nil {
		u.err = fmt.Errorf("SetStampMS: %w", err)
		return u
	}
	u.expr.Set("bystampsk", &types.AttributeValueMemberS{Value: bystampsk})
	return u
}

// SetWhen sets the When attribute.
func (u *SampleUpdate) SetWhen(when time.Time) *SampleUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(when)
	if err != nil {
		u.err = fmt.Errorf("SetWhen: %w", err)
		return u
	}
	u.expr.Set("when", av)
	return u
}

// RemoveWhen removes the When attribute from the item.
func (u *SampleUpdate) RemoveWhen() *SampleUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("when")
	return u
}

// SetBlob sets the Blob attribute.
func (u *SampleUpdate) SetBlob(blob []byte) *SampleUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(blob)
	if err != nil {
		u.err = fmt.Errorf("SetBlob: %w", err)
		return u
	}
	u.expr.Set("blob", av)
	return u
}

// RemoveBlob removes the Blob attribute from the item.
func (u *SampleUpdate) RemoveBlob() *SampleUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("blob")
	return u
}

// SetLabel sets the Label attribute.
func (u *SampleUpdate) SetLabel(label string) *SampleUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(label)
	if err != nil {
		u.err = fmt.Errorf("SetLabel: %w", err)
		return u
	}
	u.expr.Set("label", av)
	return u
}

// RemoveLabel removes the Label attribute from the item.
func (u *SampleUpdate) RemoveLabel() *SampleUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("label")
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Sample. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *SampleUpdate) Run(ctx context.Context) (*Sample, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("SampleUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("SampleUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("SampleUpdate: %w", err)
	}
	return unmarshalSample(out.Attributes)
}

// ByStampQuery is the chainable builder for the ByStamp access
// pattern. Terminate with All or Page.
type ByStampQuery struct {
	c        *EncClient
	pk       string
	skPrefix string
	cond     runtime.SKCond
	refined  bool
	desc     bool
	limit    int32
	filter   *runtime.Filter
	err      error
}

// ByStamp queries pk = "D#{Digest:hex}" on GSI ByStamp.
func (c *EncClient) ByStamp(digest [16]byte) *ByStampQuery {
	q := &ByStampQuery{c: c}
	pk, err := sampleBYSTAMPPK(digest)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	return q
}

// StampMSAfter restricts results to items with StampMS strictly
// after val, at the epochms encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *ByStampQuery) StampMSAfter(val int64) *ByStampQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeEpochMS(val)
	if err != nil {
		q.err = fmt.Errorf("StampMSAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// StampMSBefore restricts results to items with StampMS strictly
// before val, at the epochms encoding's granularity.
func (q *ByStampQuery) StampMSBefore(val int64) *ByStampQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeEpochMS(val)
	if err != nil {
		q.err = fmt.Errorf("StampMSBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredEpochMS(val)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// StampMSBetween restricts results to items with StampMS between lo
// and hi inclusive.
func (q *ByStampQuery) StampMSBetween(lo, hi int64) *ByStampQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodeEpochMS(lo)
	if err != nil {
		q.err = fmt.Errorf("StampMSBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodeEpochMS(hi)
	if err != nil {
		q.err = fmt.Errorf("StampMSBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *ByStampQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("ByStampQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *ByStampQuery) Desc() *ByStampQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *ByStampQuery) Limit(n int32) *ByStampQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *ByStampQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *ByStampQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *ByStampQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:   q.c.table,
		Index:   "ByStamp",
		PKAttr:  "bystamppk",
		PKValue: q.pk,
		SKAttr:  "bystampsk",
		SKCond:  q.cond,
		Desc:    q.desc,
		Limit:   q.limit,
		ETAttr:  "_et",
		ETValue: "sample",
		Filter:  q.filter,
	}
}

// All returns an iterator over every matching Sample, paginating
// internally. Iteration stops after yielding the first error.
func (q *ByStampQuery) All(ctx context.Context) iter.Seq2[Sample, error] {
	if q.err != nil {
		return func(yield func(Sample, error) bool) {
			var zero Sample
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalSample)
}

// Page returns one page of matching Sample items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *ByStampQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Sample, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalSample)
}

// SamplesAboveQuery is the chainable builder for the SamplesAbove access
// pattern. Terminate with All or Page.
type SamplesAboveQuery struct {
	c          *EncClient
	pk         string
	cond       runtime.SKCond
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// SamplesAbove queries pk = "S#{ID:ulid}", sk gt "V#{Ver2:pad6}" on the main index.
func (c *EncClient) SamplesAbove(id string, ver2 uint32) *SamplesAboveQuery {
	q := &SamplesAboveQuery{c: c}
	pk, err := samplePK(id)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.EncodePadUint(uint64(ver2), 6)
	if err != nil {
		q.err = fmt.Errorf("Sample sk condition {Ver2:pad6}: %w", err)
		return q
	}
	q.cond = runtime.SKAfter("V#", "V#"+cs0)
	return q
}

// Desc returns results in descending key order.
func (q *SamplesAboveQuery) Desc() *SamplesAboveQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *SamplesAboveQuery) Limit(n int32) *SamplesAboveQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *SamplesAboveQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *SamplesAboveQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *SamplesAboveQuery) ConsistentRead() *SamplesAboveQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *SamplesAboveQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "sample",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Sample, paginating
// internally. Iteration stops after yielding the first error.
func (q *SamplesAboveQuery) All(ctx context.Context) iter.Seq2[Sample, error] {
	if q.err != nil {
		return func(yield func(Sample, error) bool) {
			var zero Sample
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalSample)
}

// Page returns one page of matching Sample items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *SamplesAboveQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Sample, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalSample)
}

// SamplesEqQuery is the chainable builder for the SamplesEq access
// pattern. Terminate with All or Page.
type SamplesEqQuery struct {
	c          *EncClient
	pk         string
	cond       runtime.SKCond
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// SamplesEq queries pk = "S#{ID:ulid}", sk eq "V#{Ver2:pad6}#{Sum:hex}" on the main index.
func (c *EncClient) SamplesEq(id string, ver2 uint32, sum [8]byte) *SamplesEqQuery {
	q := &SamplesEqQuery{c: c}
	pk, err := samplePK(id)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.EncodePadUint(uint64(ver2), 6)
	if err != nil {
		q.err = fmt.Errorf("Sample sk condition {Ver2:pad6}: %w", err)
		return q
	}
	cs1 := runtime.EncodeHex(sum[:])
	q.cond = runtime.SKEq("V#" + cs0 + "#" + cs1)
	return q
}

// Desc returns results in descending key order.
func (q *SamplesEqQuery) Desc() *SamplesEqQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *SamplesEqQuery) Limit(n int32) *SamplesEqQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *SamplesEqQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *SamplesEqQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *SamplesEqQuery) ConsistentRead() *SamplesEqQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *SamplesEqQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "sample",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Sample, paginating
// internally. Iteration stops after yielding the first error.
func (q *SamplesEqQuery) All(ctx context.Context) iter.Seq2[Sample, error] {
	if q.err != nil {
		return func(yield func(Sample, error) bool) {
			var zero Sample
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalSample)
}

// Page returns one page of matching Sample items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *SamplesEqQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Sample, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalSample)
}

// SamplesFromQuery is the chainable builder for the SamplesFrom access
// pattern. Terminate with All or Page.
type SamplesFromQuery struct {
	c          *EncClient
	pk         string
	cond       runtime.SKCond
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// SamplesFrom queries pk = "S#{ID:ulid}", sk gte "V#{Ver2:pad6}" on the main index.
func (c *EncClient) SamplesFrom(id string, ver2 uint32) *SamplesFromQuery {
	q := &SamplesFromQuery{c: c}
	pk, err := samplePK(id)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.EncodePadUint(uint64(ver2), 6)
	if err != nil {
		q.err = fmt.Errorf("Sample sk condition {Ver2:pad6}: %w", err)
		return q
	}
	q.cond = runtime.SKOnOrAfter("V#", "V#"+cs0)
	return q
}

// Desc returns results in descending key order.
func (q *SamplesFromQuery) Desc() *SamplesFromQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *SamplesFromQuery) Limit(n int32) *SamplesFromQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *SamplesFromQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *SamplesFromQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *SamplesFromQuery) ConsistentRead() *SamplesFromQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *SamplesFromQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "sample",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Sample, paginating
// internally. Iteration stops after yielding the first error.
func (q *SamplesFromQuery) All(ctx context.Context) iter.Seq2[Sample, error] {
	if q.err != nil {
		return func(yield func(Sample, error) bool) {
			var zero Sample
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalSample)
}

// Page returns one page of matching Sample items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *SamplesFromQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Sample, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalSample)
}

// SamplesUntilQuery is the chainable builder for the SamplesUntil access
// pattern. Terminate with All or Page.
type SamplesUntilQuery struct {
	c          *EncClient
	pk         string
	cond       runtime.SKCond
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// SamplesUntil queries pk = "S#{ID:ulid}", sk lt "V#{Ver2:pad6}" on the main index.
func (c *EncClient) SamplesUntil(id string, ver2 uint32) *SamplesUntilQuery {
	q := &SamplesUntilQuery{c: c}
	pk, err := samplePK(id)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.EncodePadUint(uint64(ver2), 6)
	if err != nil {
		q.err = fmt.Errorf("Sample sk condition {Ver2:pad6}: %w", err)
		return q
	}
	pred, ok := runtime.PredPadUint(uint64(ver2), 6)
	q.cond = runtime.SKBefore("V#", "V#"+cs0, "V#"+pred, ok)
	return q
}

// Desc returns results in descending key order.
func (q *SamplesUntilQuery) Desc() *SamplesUntilQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *SamplesUntilQuery) Limit(n int32) *SamplesUntilQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *SamplesUntilQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *SamplesUntilQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *SamplesUntilQuery) ConsistentRead() *SamplesUntilQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *SamplesUntilQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "sample",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Sample, paginating
// internally. Iteration stops after yielding the first error.
func (q *SamplesUntilQuery) All(ctx context.Context) iter.Seq2[Sample, error] {
	if q.err != nil {
		return func(yield func(Sample, error) bool) {
			var zero Sample
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalSample)
}

// Page returns one page of matching Sample items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *SamplesUntilQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Sample, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalSample)
}

// BatchGetSamples loads Samples by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *EncClient) BatchGetSamples(ctx context.Context, keys []SampleKey, opts ...runtime.ReadOpt) ([]Sample, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := samplePK(k.ID)
		if err != nil {
			return nil, err
		}
		sk, err := sampleSK(k.Ver2, k.Sum)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Sample, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalSample(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutSamples writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *EncClient) BatchPutSamples(ctx context.Context, items []Sample) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalSample(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutSample returns a TransactWriteItem putting it (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *EncClient) TransactPutSample(it *Sample) (types.TransactWriteItem, error) {
	av, err := marshalSample(it)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteSample returns a TransactWriteItem deleting the
// Sample identified by the given key fields.
func (c *EncClient) TransactDeleteSample(id string, ver2 uint32, sum [8]byte) (types.TransactWriteItem, error) {
	pk, err := samplePK(id)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := sampleSK(ver2, sum)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
