// Package codegen emits the typed Go client from the compiled schema IR:
// key encoders, marshal/unmarshal with synthesized key attributes, CRUD
// methods, typed update builders, pattern queries, batch helpers, and item
// collections. Output is gofmt/goimports-clean and reflection-free.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"

	"golang.org/x/tools/imports"

	"github.com/ResonanceCache/ddbgen/internal/schema"
)

// Header marks every generated file.
const Header = "// Code generated by ddbgen. DO NOT EDIT.\n"

// Generate renders all generated files for the schema, keyed by file name
// (relative to the package directory). Colliding generated identifiers or
// file names fail generation rather than emitting broken code.
func Generate(s *schema.Schema) (map[string][]byte, error) {
	out := map[string][]byte{}
	write := func(name string, src []byte) error {
		if _, dup := out[name]; dup {
			return fmt.Errorf("two generated files would both be named %s (entity/table names that differ only in casing or underscores collide); rename one", name)
		}
		out[name] = src
		return nil
	}
	for _, t := range s.Tables {
		tv, err := buildTableView(t)
		if err != nil {
			return nil, err
		}
		evs := make([]*entityView, 0, len(t.Entities))
		for _, e := range t.Entities {
			ev, err := buildEntityView(t, e)
			if err != nil {
				return nil, err
			}
			evs = append(evs, ev)
		}
		if err := validateNames(tv, evs); err != nil {
			return nil, fmt.Errorf("table %q: %w", t.Name, err)
		}
		src, err := render(t.Name+"_table_gen.go", tableTmpl, tv)
		if err != nil {
			return nil, err
		}
		if err := write(t.Name+"_table_gen.go", src); err != nil {
			return nil, err
		}
		for i, e := range t.Entities {
			name := snake(e.Name) + "_gen.go"
			src, err := render(name, entityTmpl, evs[i])
			if err != nil {
				return nil, err
			}
			if err := write(name, src); err != nil {
				return nil, err
			}
		}
	}
	return out, nil
}

func render(name string, tmpl *template.Template, view any) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(Header)
	if err := tmpl.Execute(&buf, view); err != nil {
		return nil, fmt.Errorf("rendering %s: %w", name, err)
	}
	src, err := imports.Process(name, buf.Bytes(), &imports.Options{Comments: true, TabWidth: 8, TabIndent: true, FormatOnly: false})
	if err != nil {
		// Fall back to plain formatting so the syntax error is inspectable
		// in the written file.
		if fsrc, ferr := format.Source(buf.Bytes()); ferr == nil {
			return fsrc, fmt.Errorf("goimports on %s: %w", name, err)
		}
		return buf.Bytes(), fmt.Errorf("generated %s does not parse: %w", name, err)
	}
	return src, nil
}

var tableTmpl = template.Must(template.New("table").Parse(`
package {{.Package}}

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// {{.Client}} is a typed client for the single-table design on table
// {{printf "%q" .Table}}.
type {{.Client}} struct {
	ddb   runtime.DynamoDB
	table string
}

// New{{.Client}} returns a client bound to the given table name. ddb is
// usually *dynamodb.Client; any implementation of the runtime.DynamoDB
// subset works, so tests can substitute a mock and middleware can wrap.
func New{{.Client}}(ddb runtime.DynamoDB, table string) *{{.Client}} {
	return &{{.Client}}{ddb: ddb, table: table}
}

// DynamoDB returns the underlying client, the escape hatch for operations
// the generated surface does not cover.
func (c *{{.Client}}) DynamoDB() runtime.DynamoDB { return c.ddb }

// TableName returns the physical table name the client is bound to.
func (c *{{.Client}}) TableName() string { return c.table }

// {{.Iface}} is the sealed union of entity types stored in table
// {{printf "%q" .Table}}: {{range $i, $e := .Entities}}{{if $i}}, {{end}}{{$e}}{{end}}.
type {{.Iface}} interface{ is{{.Iface}}() }

// TransactWrite executes the given write items in one atomic transaction
// (thin passthrough over DynamoDB TransactWriteItems; at most 100 items).
// Build items with the TransactPut/TransactDelete helpers. A failed
// condition inside the transaction surfaces as runtime.ErrConditionFailed.
func (c *{{.Client}}) TransactWrite(ctx context.Context, items ...types.TransactWriteItem) error {
	if len(items) == 0 {
		return nil
	}
	_, err := c.ddb.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{
		TransactItems: items,
	})
	if err != nil {
		if runtime.IsTransactionConditionFailed(err) {
			// Both errors stay in the chain: match the sentinel with
			// errors.Is, or errors.As the SDK exception for its
			// CancellationReasons.
			return fmt.Errorf("TransactWrite: %w: %w", runtime.ErrConditionFailed, err)
		}
		return fmt.Errorf("TransactWrite: %w", err)
	}
	return nil
}

{{range .Partitions}}
// {{.QueryType}} queries every item in one {{printf "%q" .PKRaw}}
// partition. Terminate with Collect.
type {{.QueryType}} struct {
	c          *{{.Client}}
	pk         string
	consistent bool
	err        error
}

// {{.Name}} starts a partition query over the item collection holding
// {{range $i, $m := .Members}}{{if $i}}, {{end}}{{$m.Entity}}{{end}} items.
func (c *{{.Client}}) {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) *{{.QueryType}} {
	q := &{{.QueryType}}{c: c}
	pk, err := {{.PKFunc}}({{.PKArgs}})
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	return q
}

// ConsistentRead makes the partition query strongly consistent.
func (q *{{.QueryType}}) ConsistentRead() *{{.QueryType}} {
	q.consistent = true
	return q
}

// Collect drains the partition and dispatches every item by its
// entity-type attribute into a typed collection.
func (q *{{.QueryType}}) Collect(ctx context.Context) (*{{.Collection}}, error) {
	if q.err != nil {
		return nil, q.err
	}
	col := &{{.Collection}}{}
	spec := runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		Consistent: q.consistent,
	}
	for av, err := range runtime.QueryAllRaw(ctx, q.c.ddb, spec) {
		if err != nil {
			return nil, err
		}
		switch {
{{- range .Members}}
		case runtime.EntityType(av, {{printf "%q" .ETAttr}}) == {{printf "%q" .Type}}:
			it, err := {{.Unmarshal}}(av)
			if err != nil {
				return nil, err
			}
			col.{{.Plural}} = append(col.{{.Plural}}, *it)
{{- end}}
		default:
			col.Unknown = append(col.Unknown, av)
		}
	}
	return col, nil
}

// {{.Collection}} is the typed contents of one {{printf "%q" .PKRaw}}
// partition.
type {{.Collection}} struct {
{{- range .Members}}
	{{.Plural}} []{{.Entity}}
{{- end}}
	// Unknown holds items whose entity-type attribute matches no generated
	// entity (for example, items written by a newer schema).
	Unknown []map[string]types.AttributeValue
}
{{end}}
`))

var entityTmpl = template.Must(template.New("entity").Parse(`
package {{.Package}}

import (
	"context"
	"fmt"
	"iter"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

{{range .KeyFuncs}}
// {{.Name}} encodes the {{$.Entity}} {{.Desc}} attribute.
func {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) (string, error) {
{{- range .Steps}}
	{{.Var}}{{if .HasErr}}, err{{end}} := {{.Expr}}
{{- if .HasErr}}
	if err != nil {
		return "", fmt.Errorf("{{$.Entity}} {{.Desc}}: %w", err)
	}
{{- end}}
{{- end}}
	return {{.Return}}, nil
}
{{end}}

// {{.Entity}}Key identifies one {{.Entity}} by its key source fields.
type {{.Entity}}Key struct {
{{- range .KeyParams}}
	{{.Field}} {{.Type}}
{{- end}}
}

func ({{.Entity}}) is{{.ItemIface}}() {}

// marshal{{.Entity}} marshals {{.ItemVar}} and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshal{{.Entity}}({{.ItemVar}} *{{.Entity}}) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap({{.ItemVar}})
	if err != nil {
		return nil, fmt.Errorf("marshaling {{.Entity}}: %w", err)
	}
{{- range .KeyFuncs}}
	{{.Attr}}, err := {{.Name}}({{.FromItem}})
	if err != nil {
		return nil, err
	}
	av[{{printf "%q" .Attr}}] = &types.AttributeValueMemberS{Value: {{.Attr}}}
{{- end}}
	av[{{printf "%q" .ETAttr}}] = &types.AttributeValueMemberS{Value: {{printf "%q" .TypeString}}}
	return av, nil
}

func unmarshal{{.Entity}}(av map[string]types.AttributeValue) (*{{.Entity}}, error) {
	var {{.ItemVar}} {{.Entity}}
	if err := attributevalue.UnmarshalMap(av, &{{.ItemVar}}); err != nil {
		return nil, fmt.Errorf("unmarshaling {{.Entity}}: %w", err)
	}
	return &{{.ItemVar}}, nil
}

// Get{{.Entity}} loads the {{.Entity}} identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *{{.Client}}) Get{{.Entity}}(ctx context.Context{{range .KeyParams}}, {{.Name}} {{.Type}}{{end}}, opts ...runtime.ReadOpt) (*{{.Entity}}, error) {
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		return nil, err
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		return nil, err
	}
{{- end}}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
			"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("Get{{.Entity}}: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("Get{{.Entity}}: %w", runtime.ErrNotFound)
	}
	return unmarshal{{.Entity}}(out.Item)
}

{{if .HasVersion}}
// Put{{.Entity}} writes {{.ItemVar}} with optimistic locking on {{.VersionField}}:
// when {{.ItemVar}}.{{.VersionField}} is zero the item must not exist yet; otherwise the stored
// version must still equal it. The written item carries {{.VersionField}}+1, and
// {{.ItemVar}}.{{.VersionField}} is advanced in place on success. A lost race returns
// runtime.ErrVersionConflict.
func (c *{{.Client}}) Put{{.Entity}}(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
	expected := {{.ItemVar}}.{{.VersionField}}
	{{.ItemVar}}.{{.VersionField}} = expected + 1
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
		{{.ItemVar}}.{{.VersionField}} = expected
		return err
	}
	input := &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}
	if expected == 0 {
		input.ConditionExpression = aws.String("attribute_not_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	} else {
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": {{printf "%q" .VersionAttr}}}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt({{if .VersionConv}}int64(expected){{else}}expected{{end}}, 10)},
		}
	}
	if _, err := c.ddb.PutItem(ctx, input); err != nil {
		{{.ItemVar}}.{{.VersionField}} = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("Put{{.Entity}}: %w", runtime.ErrVersionConflict)
		}
		return fmt.Errorf("Put{{.Entity}}: %w", err)
	}
	return nil
}
{{else}}
// Put{{.Entity}} writes {{.ItemVar}} unconditionally (last writer wins).
func (c *{{.Client}}) Put{{.Entity}}(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("Put{{.Entity}}: %w", err)
	}
	return nil
}
{{end}}

// Put{{.Entity}}IfNotExists writes {{.ItemVar}} only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *{{.Client}}) Put{{.Entity}}IfNotExists(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
{{- if .HasVersion}}
	expected := {{.ItemVar}}.{{.VersionField}}
	if expected == 0 {
		{{.ItemVar}}.{{.VersionField}} = 1
	}
{{- end}}
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
{{- if .HasVersion}}
		{{.ItemVar}}.{{.VersionField}} = expected
{{- end}}
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0){{if .HasSK}} AND attribute_not_exists(#p1){{end}}"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
{{- if .HasSK}}
			"#p1": "sk",
{{- end}}
		},
	}); err != nil {
{{- if .HasVersion}}
		{{.ItemVar}}.{{.VersionField}} = expected
{{- end}}
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("Put{{.Entity}}IfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("Put{{.Entity}}IfNotExists: %w", err)
	}
	return nil
}

// Delete{{.Entity}} deletes the {{.Entity}} identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist(){{if .HasVersion}} or
// runtime.WithExpectVersion(v){{end}}.
func (c *{{.Client}}) Delete{{.Entity}}(ctx context.Context{{range .KeyParams}}, {{.Name}} {{.Type}}{{end}}, opts ...runtime.DeleteOpt) error {
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		return err
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		return err
	}
{{- end}}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
			"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
{{- if not .HasVersion}}
	if do.ExpectVersion != nil {
		return fmt.Errorf("Delete{{.Entity}}: {{.Entity}} declares no version field; WithExpectVersion is not applicable")
	}
{{- end}}
	switch {
{{- if .HasVersion}}
	case do.ExpectVersion != nil:
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": {{printf "%q" .VersionAttr}}}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt(*do.ExpectVersion, 10)},
		}
{{- end}}
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
{{- if .HasVersion}}
			if do.ExpectVersion != nil {
				return fmt.Errorf("Delete{{.Entity}}: %w", runtime.ErrVersionConflict)
			}
{{- end}}
			return fmt.Errorf("Delete{{.Entity}}: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("Delete{{.Entity}}: %w", err)
	}
	return nil
}

// {{.Entity}}Update is a typed update builder for {{.Entity}}. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type {{.Entity}}Update struct {
	c    *{{.Client}}
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
{{- if .HasVersion}}
	expectVersion *int64
{{- end}}
	err error
}

// Update{{.Entity}} starts a typed update of the {{.Entity}} identified by
// the given key fields.
func (c *{{.Client}}) Update{{.Entity}}({{range $i, $p := .KeyParams}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) *{{.Entity}}Update {
	u := &{{.Entity}}Update{c: c}
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		u.err = err
		return u
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		u.err = err
		return u
	}
{{- end}}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
		"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
	}
	return u
}

{{range .Updates}}
{{- $m := .}}
{{- if eq .Kind "set"}}
// {{.Method}} sets the {{.Field}} attribute{{if .GSISyncs}} and recomputes the
// synthesized {{range $i, $g := .GSISyncs}}{{if $i}}, {{end}}{{$g.Attr}}{{end}} key attribute{{if gt (len .GSISyncs) 1}}s{{end}} ({{range $i, $g := .GSISyncs}}{{if $i}}, {{end}}{{$g.Index}}{{end}} stays in sync){{end}}.
func (u *{{$.Entity}}Update) {{.Method}}({{.Param}} {{.Type}}) *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal({{.Param}})
	if err != nil {
		u.err = fmt.Errorf("{{.Method}}: %w", err)
		return u
	}
	u.expr.Set({{printf "%q" .Attr}}, av)
{{- range .GSISyncs}}
	{{.Attr}}, err := {{.FuncName}}({{$m.Param}})
	if err != nil {
		u.err = fmt.Errorf("{{$m.Method}}: %w", err)
		return u
	}
	u.expr.Set({{printf "%q" .Attr}}, &types.AttributeValueMemberS{Value: {{.Attr}}})
{{- end}}
	return u
}
{{- else if eq .Kind "add"}}
// {{.Method}} atomically adds delta to the {{.Field}} attribute.
func (u *{{$.Entity}}Update) {{.Method}}(delta {{.Type}}) *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	u.expr.Add({{printf "%q" .Attr}}, &types.AttributeValueMemberN{Value: {{.NumConv}}})
	return u
}
{{- else}}
// {{.Method}} removes the {{.Field}} attribute from the item.
func (u *{{$.Entity}}Update) {{.Method}}() *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	u.expr.Remove({{printf "%q" .Attr}})
	return u
}
{{- end}}
{{end}}

{{- if .HasVersion}}
// ExpectVersion conditions the update on the stored {{.VersionField}} still
// being version, so Run returns runtime.ErrVersionConflict on a lost race.
// Without it the update increments {{.VersionField}} unconditionally.
func (u *{{.Entity}}Update) ExpectVersion(version int64) *{{.Entity}}Update {
	u.expectVersion = &version
	return u
}
{{- end}}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated {{.Entity}}. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *{{.Entity}}Update) Run(ctx context.Context) (*{{.Entity}}, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("{{.Entity}}Update: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
{{- if .HasVersion}}
	u.expr.IncrementVersion({{printf "%q" .VersionAttr}})
	if u.expectVersion != nil {
		cond += " AND #p1 = :p1"
		names["#p1"] = {{printf "%q" .VersionAttr}}
		values[":p1"] = &types.AttributeValueMemberN{Value: strconv.FormatInt(*u.expectVersion, 10)}
	}
{{- end}}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
{{- if .HasVersion}}
			if u.expectVersion != nil {
				return nil, fmt.Errorf("{{.Entity}}Update: %w", runtime.ErrVersionConflict)
			}
{{- end}}
			return nil, fmt.Errorf("{{.Entity}}Update: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("{{.Entity}}Update: %w", err)
	}
	return unmarshal{{.Entity}}(out.Attributes)
}

{{range .Patterns}}
// {{.QueryType}} is the chainable builder for the {{.Name}} access
// pattern. Terminate with All or Page.
type {{.QueryType}} struct {
	c *{{.Client}}
	pk string
{{- if .HasSKStore}}
	skPrefix string
{{- end}}
{{- if .HasCond}}
	cond runtime.SKCond
{{- end}}
{{- if .Range}}
	refined bool
{{- end}}
	desc   bool
	limit  int32
	filter *runtime.Filter
{{- if .HasConsistent}}
	consistent bool
{{- end}}
	err error
}

// {{.Name}} queries {{.Doc}}.
func (c *{{.Client}}) {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) *{{.QueryType}} {
	q := &{{.QueryType}}{c: c}
	pk, err := {{.PKFunc}}({{.PKArgs}})
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
{{- range .CondSteps}}
	{{.Var}}{{if .HasErr}}, err{{end}} := {{.Expr}}
{{- if .HasErr}}
	if err != nil {
		q.err = fmt.Errorf("{{$.Entity}} {{.Desc}}: %w", err)
		return q
	}
{{- end}}
{{- end}}
{{- if or (eq .CondKind "begins") (eq .CondKind "implicit")}}
	q.skPrefix = {{.ValExpr}}
	q.cond = runtime.SKBegins(q.skPrefix)
{{- else if eq .CondKind "eq"}}
	q.cond = runtime.SKEq({{.ValExpr}})
{{- else if eq .CondKind "gt"}}
	q.cond = runtime.SKAfter({{.ScopeQ}}, {{.ValExpr}})
{{- else if eq .CondKind "gte"}}
	q.cond = runtime.SKOnOrAfter({{.ScopeQ}}, {{.ValExpr}})
{{- else if eq .CondKind "lte"}}
	q.cond = runtime.SKOnOrBefore({{.ScopeQ}}, {{.ValExpr}})
{{- else if eq .CondKind "lt"}}
	pred, ok := {{.PredCall}}
	q.cond = runtime.SKBefore({{.ScopeQ}}, {{.ValExpr}}, {{.PredFull}}, ok)
{{- end}}
	return q
}

{{$q := .}}
{{- with .Range}}
// {{.Base}}After restricts results to items with {{.Field}} strictly
// after val, at the {{.Encoder}} encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *{{$q.QueryType}}) {{.Base}}After(val {{.ParamType}}) *{{$q.QueryType}} {
	if !q.beginRefine() {
		return q
	}
{{- if .EncHasErr}}
	enc, err := {{.Enc "val"}}
	if err != nil {
		q.err = fmt.Errorf("{{.Base}}After: %w", err)
		return q
	}
{{- else}}
	enc := {{.Enc "val"}}
{{- end}}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// {{.Base}}Before restricts results to items with {{.Field}} strictly
// before val, at the {{.Encoder}} encoding's granularity.
func (q *{{$q.QueryType}}) {{.Base}}Before(val {{.ParamType}}) *{{$q.QueryType}} {
	if !q.beginRefine() {
		return q
	}
{{- if .EncHasErr}}
	enc, err := {{.Enc "val"}}
	if err != nil {
		q.err = fmt.Errorf("{{.Base}}Before: %w", err)
		return q
	}
{{- else}}
	enc := {{.Enc "val"}}
{{- end}}
	pred, ok := {{.Pred "val"}}
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// {{.Base}}Between restricts results to items with {{.Field}} between lo
// and hi inclusive.
func (q *{{$q.QueryType}}) {{.Base}}Between(lo, hi {{.ParamType}}) *{{$q.QueryType}} {
	if !q.beginRefine() {
		return q
	}
{{- if .EncHasErr}}
	encLo, err := {{.Enc "lo"}}
	if err != nil {
		q.err = fmt.Errorf("{{.Base}}Between: %w", err)
		return q
	}
	encHi, err := {{.Enc "hi"}}
	if err != nil {
		q.err = fmt.Errorf("{{.Base}}Between: %w", err)
		return q
	}
{{- else}}
	encLo := {{.Enc "lo"}}
	encHi := {{.Enc "hi"}}
{{- end}}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *{{$q.QueryType}}) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("{{$q.QueryType}}: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}
{{- end}}

// Desc returns results in descending key order.
func (q *{{.QueryType}}) Desc() *{{.QueryType}} {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *{{.QueryType}}) Limit(n int32) *{{.QueryType}} {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *{{.QueryType}}) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *{{.QueryType}} {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

{{if .HasConsistent}}
// ConsistentRead makes the query strongly consistent.
func (q *{{.QueryType}}) ConsistentRead() *{{.QueryType}} {
	q.consistent = true
	return q
}
{{end}}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *{{.QueryType}}) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table: q.c.table,
{{- if .Index}}
		Index: {{printf "%q" .Index}},
{{- end}}
		PKAttr:  {{printf "%q" .PKAttr}},
		PKValue: q.pk,
{{- if .HasCond}}
		SKAttr: {{printf "%q" .SKAttr}},
		SKCond: q.cond,
{{- end}}
		Desc:    q.desc,
		Limit:   q.limit,
		ETAttr:  {{printf "%q" $.ETAttr}},
		ETValue: {{printf "%q" $.TypeString}},
		Filter:  q.filter,
{{- if .HasConsistent}}
		Consistent: q.consistent,
{{- end}}
	}
}

// All returns an iterator over every matching {{.Entity}}, paginating
// internally. Iteration stops after yielding the first error.
func (q *{{.QueryType}}) All(ctx context.Context) iter.Seq2[{{.Entity}}, error] {
	if q.err != nil {
		return func(yield func({{.Entity}}, error) bool) {
			var zero {{.Entity}}
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshal{{.Entity}})
}

// Page returns one page of matching {{.Entity}} items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *{{.QueryType}}) Page(ctx context.Context, cursor runtime.Cursor) ([]{{.Entity}}, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshal{{.Entity}})
}
{{end}}

// BatchGet{{.Batch.Plural}} loads {{.Batch.Plural}} by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *{{.Client}}) BatchGet{{.Batch.Plural}}(ctx context.Context, keys []{{.Entity}}Key, opts ...runtime.ReadOpt) ([]{{.Entity}}, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := {{.Batch.PKFunc}}({{.Batch.PKKey}})
		if err != nil {
			return nil, err
		}
{{- if .Batch.HasSK}}
		sk, err := {{.Batch.SKFunc}}({{.Batch.SKKey}})
		if err != nil {
			return nil, err
		}
{{- end}}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .Batch.HasSK}}
			"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]{{.Entity}}, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshal{{.Entity}}(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPut{{.Batch.Plural}} writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.{{if .Batch.HasVer}} Batch writes bypass
// optimistic locking: items are written with their current {{.VersionField}} as-is.{{end}}
func (c *{{.Client}}) BatchPut{{.Batch.Plural}}(ctx context.Context, items []{{.Entity}}) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshal{{.Entity}}(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPut{{.Entity}} returns a TransactWriteItem putting {{.ItemVar}} (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *{{.Client}}) TransactPut{{.Entity}}({{.ItemVar}} *{{.Entity}}) (types.TransactWriteItem, error) {
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDelete{{.Entity}} returns a TransactWriteItem deleting the
// {{.Entity}} identified by the given key fields.
func (c *{{.Client}}) TransactDelete{{.Entity}}({{range $i, $p := .KeyParams}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) (types.TransactWriteItem, error) {
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		return types.TransactWriteItem{}, err
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		return types.TransactWriteItem{}, err
	}
{{- end}}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
				"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
			},
		},
	}, nil
}
`))
