// Package codegen emits the typed Go client from the compiled schema IR:
// key encoders, marshal/unmarshal with synthesized key attributes, CRUD
// methods, typed update builders, pattern queries, batch helpers, and item
// collections. Output is gofmt/goimports-clean and reflection-free.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"text/template"

	"golang.org/x/tools/imports"

	"github.com/ResonanceCache/ddbgen/internal/schema"
)

// Header marks every generated file.
const Header = "// Code generated by ddbgen. DO NOT EDIT.\n"

// Generate renders all generated files for the schema, keyed by file name
// (relative to the package directory).
func Generate(s *schema.Schema) (map[string][]byte, error) {
	out := map[string][]byte{}
	for _, t := range s.Tables {
		name := t.Name + "_table_gen.go"
		src, err := render(name, tableTmpl, buildTableView(t))
		if err != nil {
			return nil, err
		}
		out[name] = src
		for _, e := range t.Entities {
			ev, err := buildEntityView(t, e)
			if err != nil {
				return nil, err
			}
			name := snake(e.Name) + "_gen.go"
			src, err := render(name, entityTmpl, ev)
			if err != nil {
				return nil, err
			}
			out[name] = src
		}
	}
	return out, nil
}

func render(name string, tmpl *template.Template, view any) ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(Header)
	if err := tmpl.Execute(&buf, view); err != nil {
		return nil, fmt.Errorf("rendering %s: %w", name, err)
	}
	src, err := imports.Process(name, buf.Bytes(), &imports.Options{Comments: true, TabWidth: 8, TabIndent: true, FormatOnly: false})
	if err != nil {
		// Fall back to plain formatting so the syntax error is inspectable
		// in the written file.
		if fsrc, ferr := format.Source(buf.Bytes()); ferr == nil {
			return fsrc, fmt.Errorf("goimports on %s: %w", name, err)
		}
		return buf.Bytes(), fmt.Errorf("generated %s does not parse: %w", name, err)
	}
	return src, nil
}

var tableTmpl = template.Must(template.New("table").Parse(`
package {{.Package}}

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

// {{.Client}} is a typed client for the single-table design on table
// {{printf "%q" .Table}}.
type {{.Client}} struct {
	ddb   *dynamodb.Client
	table string
}

// New{{.Client}} returns a client bound to the given table name.
func New{{.Client}}(ddb *dynamodb.Client, table string) *{{.Client}} {
	return &{{.Client}}{ddb: ddb, table: table}
}

// {{.Iface}} is the sealed union of entity types stored in table
// {{printf "%q" .Table}}: {{range $i, $e := .Entities}}{{if $i}}, {{end}}{{$e}}{{end}}.
type {{.Iface}} interface{ is{{.Iface}}() }
`))

var entityTmpl = template.Must(template.New("entity").Parse(`
package {{.Package}}

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

{{range .KeyFuncs}}
// {{.Name}} encodes the {{$.Entity}} {{.Desc}} attribute.
func {{.Name}}({{range $i, $p := .Params}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) (string, error) {
{{- range .Steps}}
	{{.Var}}{{if .HasErr}}, err{{end}} := {{.Expr}}
{{- if .HasErr}}
	if err != nil {
		return "", fmt.Errorf("{{$.Entity}} {{.Desc}}: %w", err)
	}
{{- end}}
{{- end}}
	return {{.Return}}, nil
}
{{end}}

// {{.Entity}}Key identifies one {{.Entity}} by its key source fields.
type {{.Entity}}Key struct {
{{- range .KeyParams}}
	{{.Field}} {{.Type}}
{{- end}}
}

func ({{.Entity}}) is{{.ItemIface}}() {}

// marshal{{.Entity}} marshals {{.ItemVar}} and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshal{{.Entity}}({{.ItemVar}} *{{.Entity}}) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap({{.ItemVar}})
	if err != nil {
		return nil, fmt.Errorf("marshaling {{.Entity}}: %w", err)
	}
{{- range .KeyFuncs}}
	{{.Attr}}, err := {{.Name}}({{.FromItem}})
	if err != nil {
		return nil, err
	}
	av[{{printf "%q" .Attr}}] = &types.AttributeValueMemberS{Value: {{.Attr}}}
{{- end}}
	av[{{printf "%q" .ETAttr}}] = &types.AttributeValueMemberS{Value: {{printf "%q" .TypeString}}}
	return av, nil
}

func unmarshal{{.Entity}}(av map[string]types.AttributeValue) (*{{.Entity}}, error) {
	var {{.ItemVar}} {{.Entity}}
	if err := attributevalue.UnmarshalMap(av, &{{.ItemVar}}); err != nil {
		return nil, fmt.Errorf("unmarshaling {{.Entity}}: %w", err)
	}
	return &{{.ItemVar}}, nil
}

// Get{{.Entity}} loads the {{.Entity}} identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists.
func (c *{{.Client}}) Get{{.Entity}}(ctx context.Context{{range .KeyParams}}, {{.Name}} {{.Type}}{{end}}) (*{{.Entity}}, error) {
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		return nil, err
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		return nil, err
	}
{{- end}}
	out, err := c.ddb.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
			"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
		},
	})
	if err != nil {
		return nil, fmt.Errorf("Get{{.Entity}}: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("Get{{.Entity}}: %w", runtime.ErrNotFound)
	}
	return unmarshal{{.Entity}}(out.Item)
}

{{if .HasVersion}}
// Put{{.Entity}} writes {{.ItemVar}} with optimistic locking on {{.VersionField}}:
// when {{.ItemVar}}.{{.VersionField}} is zero the item must not exist yet; otherwise the stored
// version must still equal it. The written item carries {{.VersionField}}+1, and
// {{.ItemVar}}.{{.VersionField}} is advanced in place on success. A lost race returns
// runtime.ErrVersionConflict.
func (c *{{.Client}}) Put{{.Entity}}(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
	expected := {{.ItemVar}}.{{.VersionField}}
	{{.ItemVar}}.{{.VersionField}} = expected + 1
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
		{{.ItemVar}}.{{.VersionField}} = expected
		return err
	}
	input := &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}
	if expected == 0 {
		input.ConditionExpression = aws.String("attribute_not_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	} else {
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": {{printf "%q" .VersionAttr}}}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt({{if .VersionConv}}int64(expected){{else}}expected{{end}}, 10)},
		}
	}
	if _, err := c.ddb.PutItem(ctx, input); err != nil {
		{{.ItemVar}}.{{.VersionField}} = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("Put{{.Entity}}: %w", runtime.ErrVersionConflict)
		}
		return fmt.Errorf("Put{{.Entity}}: %w", err)
	}
	return nil
}
{{else}}
// Put{{.Entity}} writes {{.ItemVar}} unconditionally (last writer wins).
func (c *{{.Client}}) Put{{.Entity}}(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("Put{{.Entity}}: %w", err)
	}
	return nil
}
{{end}}

// Put{{.Entity}}IfNotExists writes {{.ItemVar}} only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *{{.Client}}) Put{{.Entity}}IfNotExists(ctx context.Context, {{.ItemVar}} *{{.Entity}}) error {
{{- if .HasVersion}}
	expected := {{.ItemVar}}.{{.VersionField}}
	if expected == 0 {
		{{.ItemVar}}.{{.VersionField}} = 1
	}
{{- end}}
	av, err := marshal{{.Entity}}({{.ItemVar}})
	if err != nil {
{{- if .HasVersion}}
		{{.ItemVar}}.{{.VersionField}} = expected
{{- end}}
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0){{if .HasSK}} AND attribute_not_exists(#p1){{end}}"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
{{- if .HasSK}}
			"#p1": "sk",
{{- end}}
		},
	}); err != nil {
{{- if .HasVersion}}
		{{.ItemVar}}.{{.VersionField}} = expected
{{- end}}
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("Put{{.Entity}}IfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("Put{{.Entity}}IfNotExists: %w", err)
	}
	return nil
}

// Delete{{.Entity}} deletes the {{.Entity}} identified by the given key
// fields. Deleting a missing item is not an error.
func (c *{{.Client}}) Delete{{.Entity}}(ctx context.Context{{range .KeyParams}}, {{.Name}} {{.Type}}{{end}}) error {
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		return err
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		return err
	}
{{- end}}
	if _, err := c.ddb.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
			"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
		},
	}); err != nil {
		return fmt.Errorf("Delete{{.Entity}}: %w", err)
	}
	return nil
}

// {{.Entity}}Update is a typed update builder for {{.Entity}}. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type {{.Entity}}Update struct {
	c    *{{.Client}}
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
{{- if .HasVersion}}
	expectVersion *int64
{{- end}}
	err error
}

// Update{{.Entity}} starts a typed update of the {{.Entity}} identified by
// the given key fields.
func (c *{{.Client}}) Update{{.Entity}}({{range $i, $p := .KeyParams}}{{if $i}}, {{end}}{{$p.Name}} {{$p.Type}}{{end}}) *{{.Entity}}Update {
	u := &{{.Entity}}Update{c: c}
	pk, err := {{.PKFunc.Name}}({{.PKFunc.FromParam}})
	if err != nil {
		u.err = err
		return u
	}
{{- if .HasSK}}
	sk, err := {{.SKFunc.Name}}({{.SKFunc.FromParam}})
	if err != nil {
		u.err = err
		return u
	}
{{- end}}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
{{- if .HasSK}}
		"sk": &types.AttributeValueMemberS{Value: sk},
{{- end}}
	}
	return u
}

{{range .Updates}}
{{- $m := .}}
{{- if eq .Kind "set"}}
// {{.Method}} sets the {{.Field}} attribute{{if .GSISyncs}} and recomputes the
// synthesized {{range $i, $g := .GSISyncs}}{{if $i}}, {{end}}{{$g.Attr}}{{end}} key attribute{{if gt (len .GSISyncs) 1}}s{{end}} ({{range $i, $g := .GSISyncs}}{{if $i}}, {{end}}{{$g.Index}}{{end}} stays in sync){{end}}.
func (u *{{$.Entity}}Update) {{.Method}}({{.Param}} {{.Type}}) *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal({{.Param}})
	if err != nil {
		u.err = fmt.Errorf("{{.Method}}: %w", err)
		return u
	}
	u.expr.Set({{printf "%q" .Attr}}, av)
{{- range .GSISyncs}}
	{{.Attr}}, err := {{.FuncName}}({{$m.Param}})
	if err != nil {
		u.err = fmt.Errorf("{{$m.Method}}: %w", err)
		return u
	}
	u.expr.Set({{printf "%q" .Attr}}, &types.AttributeValueMemberS{Value: {{.Attr}}})
{{- end}}
	return u
}
{{- else if eq .Kind "add"}}
// {{.Method}} atomically adds delta to the {{.Field}} attribute.
func (u *{{$.Entity}}Update) {{.Method}}(delta {{.Type}}) *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	u.expr.Add({{printf "%q" .Attr}}, &types.AttributeValueMemberN{Value: {{.NumConv}}})
	return u
}
{{- else}}
// {{.Method}} removes the {{.Field}} attribute from the item.
func (u *{{$.Entity}}Update) {{.Method}}() *{{$.Entity}}Update {
	if u.err != nil {
		return u
	}
	u.expr.Remove({{printf "%q" .Attr}})
	return u
}
{{- end}}
{{end}}

{{- if .HasVersion}}
// ExpectVersion conditions the update on the stored {{.VersionField}} still
// being version, so Run returns runtime.ErrVersionConflict on a lost race.
// Without it the update increments {{.VersionField}} unconditionally.
func (u *{{.Entity}}Update) ExpectVersion(version int64) *{{.Entity}}Update {
	u.expectVersion = &version
	return u
}
{{- end}}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated {{.Entity}}. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *{{.Entity}}Update) Run(ctx context.Context) (*{{.Entity}}, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("{{.Entity}}Update: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
{{- if .HasVersion}}
	u.expr.IncrementVersion({{printf "%q" .VersionAttr}})
	if u.expectVersion != nil {
		cond += " AND #p1 = :p1"
		names["#p1"] = {{printf "%q" .VersionAttr}}
		values[":p1"] = &types.AttributeValueMemberN{Value: strconv.FormatInt(*u.expectVersion, 10)}
	}
{{- end}}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
{{- if .HasVersion}}
			if u.expectVersion != nil {
				return nil, fmt.Errorf("{{.Entity}}Update: %w", runtime.ErrVersionConflict)
			}
{{- end}}
			return nil, fmt.Errorf("{{.Entity}}Update: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("{{.Entity}}Update: %w", err)
	}
	return unmarshal{{.Entity}}(out.Attributes)
}
`))
