// Code generated by ddbgen. DO NOT EDIT.

package bounds

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// BxClient is a typed client for the single-table design on table
// "bx".
type BxClient struct {
	ddb   runtime.DynamoDB
	table string
}

// NewBxClient returns a client bound to the given table name. ddb is
// usually *dynamodb.Client; any implementation of the runtime.DynamoDB
// subset works, so tests can substitute a mock and middleware can wrap.
func NewBxClient(ddb runtime.DynamoDB, table string) *BxClient {
	return &BxClient{ddb: ddb, table: table}
}

// DynamoDB returns the underlying client, the escape hatch for operations
// the generated surface does not cover.
func (c *BxClient) DynamoDB() runtime.DynamoDB { return c.ddb }

// TableName returns the physical table name the client is bound to.
func (c *BxClient) TableName() string { return c.table }

// BxItem is the sealed union of entity types stored in table
// "bx": Event, Job, Note.
type BxItem interface{ isBxItem() }

// TransactWrite executes the given write items in one atomic transaction
// (thin passthrough over DynamoDB TransactWriteItems; at most 100 items).
// Build items with the TransactPut/TransactDelete helpers. A failed
// condition inside the transaction surfaces as runtime.ErrConditionFailed.
func (c *BxClient) TransactWrite(ctx context.Context, items ...types.TransactWriteItem) error {
	if len(items) == 0 {
		return nil
	}
	_, err := c.ddb.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{
		TransactItems: items,
	})
	if err != nil {
		if runtime.IsTransactionConditionFailed(err) {
			// Both errors stay in the chain: match the sentinel with
			// errors.Is, or errors.As the SDK exception for its
			// CancellationReasons.
			return fmt.Errorf("TransactWrite: %w: %w", runtime.ErrConditionFailed, err)
		}
		return fmt.Errorf("TransactWrite: %w", err)
	}
	return nil
}

// TenPartitionQuery queries every item in one "TEN#{Ten}"
// partition. Terminate with Collect.
type TenPartitionQuery struct {
	c          *BxClient
	pk         string
	consistent bool
	err        error
}

// TenPartition starts a partition query over the item collection holding
// Event, Job, Note items.
func (c *BxClient) TenPartition(ten string) *TenPartitionQuery {
	q := &TenPartitionQuery{c: c}
	pk, err := eventPK(ten)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	return q
}

// ConsistentRead makes the partition query strongly consistent.
func (q *TenPartitionQuery) ConsistentRead() *TenPartitionQuery {
	q.consistent = true
	return q
}

// Collect drains the partition and dispatches every item by its
// entity-type attribute into a typed collection.
func (q *TenPartitionQuery) Collect(ctx context.Context) (*TenCollection, error) {
	if q.err != nil {
		return nil, q.err
	}
	col := &TenCollection{}
	spec := runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		Consistent: q.consistent,
	}
	for av, err := range runtime.QueryAllRaw(ctx, q.c.ddb, spec) {
		if err != nil {
			return nil, err
		}
		switch {
		case runtime.EntityType(av, "_et") == "event":
			it, err := unmarshalEvent(av)
			if err != nil {
				return nil, err
			}
			col.Events = append(col.Events, *it)
		case runtime.EntityType(av, "_et") == "job":
			it, err := unmarshalJob(av)
			if err != nil {
				return nil, err
			}
			col.Jobs = append(col.Jobs, *it)
		case runtime.EntityType(av, "_et") == "note":
			it, err := unmarshalNote(av)
			if err != nil {
				return nil, err
			}
			col.Notes = append(col.Notes, *it)
		default:
			col.Unknown = append(col.Unknown, av)
		}
	}
	return col, nil
}

// TenCollection is the typed contents of one "TEN#{Ten}"
// partition.
type TenCollection struct {
	Events []Event
	Jobs   []Job
	Notes  []Note
	// Unknown holds items whose entity-type attribute matches no generated
	// entity (for example, items written by a newer schema).
	Unknown []map[string]types.AttributeValue
}
