// Code generated by ddbgen. DO NOT EDIT.

package bounds

import (
	"context"
	"fmt"
	"iter"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// eventPK encodes the Event pk ("TEN#{Ten}") attribute.
func eventPK(ten string) (string, error) {
	s0, err := runtime.CheckSegment(ten)
	if err != nil {
		return "", fmt.Errorf("Event pk {Ten}: %w", err)
	}
	return "TEN#" + s0, nil
}

// eventSK encodes the Event sk ("{At:pad4}") attribute.
func eventSK(at int64) (string, error) {
	s0, err := runtime.EncodePad(at, 4)
	if err != nil {
		return "", fmt.Errorf("Event sk {At:pad4}: %w", err)
	}
	return s0, nil
}

// EventKey identifies one Event by its key source fields.
type EventKey struct {
	Ten string
	At  int64
}

func (Event) isBxItem() {}

// marshalEvent marshals e and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalEvent(e *Event) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(e)
	if err != nil {
		return nil, fmt.Errorf("marshaling Event: %w", err)
	}
	pk, err := eventPK(e.Ten)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := eventSK(e.At)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "event"}
	return av, nil
}

func unmarshalEvent(av map[string]types.AttributeValue) (*Event, error) {
	var e Event
	if err := attributevalue.UnmarshalMap(av, &e); err != nil {
		return nil, fmt.Errorf("unmarshaling Event: %w", err)
	}
	return &e, nil
}

// GetEvent loads the Event identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *BxClient) GetEvent(ctx context.Context, ten string, at int64, opts ...runtime.ReadOpt) (*Event, error) {
	pk, err := eventPK(ten)
	if err != nil {
		return nil, err
	}
	sk, err := eventSK(at)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetEvent: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetEvent: %w", runtime.ErrNotFound)
	}
	return unmarshalEvent(out.Item)
}

// PutEvent writes e unconditionally (last writer wins).
func (c *BxClient) PutEvent(ctx context.Context, e *Event) error {
	av, err := marshalEvent(e)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutEvent: %w", err)
	}
	return nil
}

// PutEventIfNotExists writes e only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *BxClient) PutEventIfNotExists(ctx context.Context, e *Event) error {
	av, err := marshalEvent(e)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutEventIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutEventIfNotExists: %w", err)
	}
	return nil
}

// DeleteEvent deletes the Event identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *BxClient) DeleteEvent(ctx context.Context, ten string, at int64, opts ...runtime.DeleteOpt) error {
	pk, err := eventPK(ten)
	if err != nil {
		return err
	}
	sk, err := eventSK(at)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteEvent: Event declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteEvent: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteEvent: %w", err)
	}
	return nil
}

// EventUpdate is a typed update builder for Event. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type EventUpdate struct {
	c    *BxClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateEvent starts a typed update of the Event identified by
// the given key fields.
func (c *BxClient) UpdateEvent(ten string, at int64) *EventUpdate {
	u := &EventUpdate{c: c}
	pk, err := eventPK(ten)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := eventSK(at)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Event. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *EventUpdate) Run(ctx context.Context) (*Event, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("EventUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("EventUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("EventUpdate: %w", err)
	}
	return unmarshalEvent(out.Attributes)
}

// EventsQuery is the chainable builder for the Events access
// pattern. Terminate with All or Page.
type EventsQuery struct {
	c          *BxClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	refined    bool
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// Events queries pk = "TEN#{Ten}" on the main index.
func (c *BxClient) Events(ten string) *EventsQuery {
	q := &EventsQuery{c: c}
	pk, err := eventPK(ten)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	return q
}

// AtAfter restricts results to items with At strictly
// after val, at the pad4 encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *EventsQuery) AtAfter(val int64) *EventsQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("AtAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// AtBefore restricts results to items with At strictly
// before val, at the pad4 encoding's granularity.
func (q *EventsQuery) AtBefore(val int64) *EventsQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("AtBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredPad(val, 4)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// AtBetween restricts results to items with At between lo
// and hi inclusive.
func (q *EventsQuery) AtBetween(lo, hi int64) *EventsQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodePad(lo, 4)
	if err != nil {
		q.err = fmt.Errorf("AtBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodePad(hi, 4)
	if err != nil {
		q.err = fmt.Errorf("AtBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *EventsQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("EventsQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *EventsQuery) Desc() *EventsQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *EventsQuery) Limit(n int32) *EventsQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *EventsQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *EventsQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *EventsQuery) ConsistentRead() *EventsQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *EventsQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "event",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Event, paginating
// internally. Iteration stops after yielding the first error.
func (q *EventsQuery) All(ctx context.Context) iter.Seq2[Event, error] {
	if q.err != nil {
		return func(yield func(Event, error) bool) {
			var zero Event
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalEvent)
}

// Page returns one page of matching Event items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *EventsQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Event, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalEvent)
}

// BatchGetEvents loads Events by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *BxClient) BatchGetEvents(ctx context.Context, keys []EventKey, opts ...runtime.ReadOpt) ([]Event, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := eventPK(k.Ten)
		if err != nil {
			return nil, err
		}
		sk, err := eventSK(k.At)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Event, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalEvent(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutEvents writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *BxClient) BatchPutEvents(ctx context.Context, items []Event) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalEvent(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutEvent returns a TransactWriteItem putting e (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *BxClient) TransactPutEvent(e *Event) (types.TransactWriteItem, error) {
	av, err := marshalEvent(e)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteEvent returns a TransactWriteItem deleting the
// Event identified by the given key fields.
func (c *BxClient) TransactDeleteEvent(ten string, at int64) (types.TransactWriteItem, error) {
	pk, err := eventPK(ten)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := eventSK(at)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
