// Code generated by ddbgen. DO NOT EDIT.

package bounds

import (
	"context"
	"fmt"
	"iter"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// jobPK encodes the Job pk ("TEN#{Ten}") attribute.
func jobPK(ten string) (string, error) {
	s0, err := runtime.CheckSegment(ten)
	if err != nil {
		return "", fmt.Errorf("Job pk {Ten}: %w", err)
	}
	return "TEN#" + s0, nil
}

// jobSK encodes the Job sk ("JOB#{Seq:pad4}#{Sub:pad4}") attribute.
func jobSK(seq int64, sub int64) (string, error) {
	s0, err := runtime.EncodePad(seq, 4)
	if err != nil {
		return "", fmt.Errorf("Job sk {Seq:pad4}: %w", err)
	}
	s1, err := runtime.EncodePad(sub, 4)
	if err != nil {
		return "", fmt.Errorf("Job sk {Sub:pad4}: %w", err)
	}
	return "JOB#" + s0 + "#" + s1, nil
}

// JobKey identifies one Job by its key source fields.
type JobKey struct {
	Ten string
	Seq int64
	Sub int64
}

func (Job) isBxItem() {}

// marshalJob marshals j and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalJob(j *Job) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(j)
	if err != nil {
		return nil, fmt.Errorf("marshaling Job: %w", err)
	}
	pk, err := jobPK(j.Ten)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := jobSK(j.Seq, j.Sub)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "job"}
	return av, nil
}

func unmarshalJob(av map[string]types.AttributeValue) (*Job, error) {
	var j Job
	if err := attributevalue.UnmarshalMap(av, &j); err != nil {
		return nil, fmt.Errorf("unmarshaling Job: %w", err)
	}
	return &j, nil
}

// GetJob loads the Job identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *BxClient) GetJob(ctx context.Context, ten string, seq int64, sub int64, opts ...runtime.ReadOpt) (*Job, error) {
	pk, err := jobPK(ten)
	if err != nil {
		return nil, err
	}
	sk, err := jobSK(seq, sub)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetJob: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetJob: %w", runtime.ErrNotFound)
	}
	return unmarshalJob(out.Item)
}

// PutJob writes j unconditionally (last writer wins).
func (c *BxClient) PutJob(ctx context.Context, j *Job) error {
	av, err := marshalJob(j)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutJob: %w", err)
	}
	return nil
}

// PutJobIfNotExists writes j only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *BxClient) PutJobIfNotExists(ctx context.Context, j *Job) error {
	av, err := marshalJob(j)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutJobIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutJobIfNotExists: %w", err)
	}
	return nil
}

// DeleteJob deletes the Job identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *BxClient) DeleteJob(ctx context.Context, ten string, seq int64, sub int64, opts ...runtime.DeleteOpt) error {
	pk, err := jobPK(ten)
	if err != nil {
		return err
	}
	sk, err := jobSK(seq, sub)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteJob: Job declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteJob: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteJob: %w", err)
	}
	return nil
}

// JobUpdate is a typed update builder for Job. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type JobUpdate struct {
	c    *BxClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateJob starts a typed update of the Job identified by
// the given key fields.
func (c *BxClient) UpdateJob(ten string, seq int64, sub int64) *JobUpdate {
	u := &JobUpdate{c: c}
	pk, err := jobPK(ten)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := jobSK(seq, sub)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Job. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *JobUpdate) Run(ctx context.Context) (*Job, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("JobUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("JobUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("JobUpdate: %w", err)
	}
	return unmarshalJob(out.Attributes)
}

// JobsDeepQuery is the chainable builder for the JobsDeep access
// pattern. Terminate with All or Page.
type JobsDeepQuery struct {
	c          *BxClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	refined    bool
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// JobsDeep queries pk = "TEN#{Ten}", sk begins "JOB#{Seq:pad4}" on the main index.
func (c *BxClient) JobsDeep(ten string, seq int64) *JobsDeepQuery {
	q := &JobsDeepQuery{c: c}
	pk, err := jobPK(ten)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	cs0, err := runtime.EncodePad(seq, 4)
	if err != nil {
		q.err = fmt.Errorf("Job sk condition {Seq:pad4}: %w", err)
		return q
	}
	q.skPrefix = "JOB#" + cs0 + "#"
	q.cond = runtime.SKBegins(q.skPrefix)
	return q
}

// SubAfter restricts results to items with Sub strictly
// after val, at the pad4 encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *JobsDeepQuery) SubAfter(val int64) *JobsDeepQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SubAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// SubBefore restricts results to items with Sub strictly
// before val, at the pad4 encoding's granularity.
func (q *JobsDeepQuery) SubBefore(val int64) *JobsDeepQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SubBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredPad(val, 4)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// SubBetween restricts results to items with Sub between lo
// and hi inclusive.
func (q *JobsDeepQuery) SubBetween(lo, hi int64) *JobsDeepQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodePad(lo, 4)
	if err != nil {
		q.err = fmt.Errorf("SubBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodePad(hi, 4)
	if err != nil {
		q.err = fmt.Errorf("SubBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *JobsDeepQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("JobsDeepQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *JobsDeepQuery) Desc() *JobsDeepQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *JobsDeepQuery) Limit(n int32) *JobsDeepQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *JobsDeepQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *JobsDeepQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *JobsDeepQuery) ConsistentRead() *JobsDeepQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *JobsDeepQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "job",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Job, paginating
// internally. Iteration stops after yielding the first error.
func (q *JobsDeepQuery) All(ctx context.Context) iter.Seq2[Job, error] {
	if q.err != nil {
		return func(yield func(Job, error) bool) {
			var zero Job
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalJob)
}

// Page returns one page of matching Job items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *JobsDeepQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Job, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalJob)
}

// JobsNoDelimQuery is the chainable builder for the JobsNoDelim access
// pattern. Terminate with All or Page.
type JobsNoDelimQuery struct {
	c          *BxClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	refined    bool
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// JobsNoDelim queries pk = "TEN#{Ten}", sk begins "JOB" on the main index.
func (c *BxClient) JobsNoDelim(ten string) *JobsNoDelimQuery {
	q := &JobsNoDelimQuery{c: c}
	pk, err := jobPK(ten)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	q.skPrefix = "JOB#"
	q.cond = runtime.SKBegins(q.skPrefix)
	return q
}

// SeqAfter restricts results to items with Seq strictly
// after val, at the pad4 encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *JobsNoDelimQuery) SeqAfter(val int64) *JobsNoDelimQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// SeqBefore restricts results to items with Seq strictly
// before val, at the pad4 encoding's granularity.
func (q *JobsNoDelimQuery) SeqBefore(val int64) *JobsNoDelimQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredPad(val, 4)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// SeqBetween restricts results to items with Seq between lo
// and hi inclusive.
func (q *JobsNoDelimQuery) SeqBetween(lo, hi int64) *JobsNoDelimQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodePad(lo, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodePad(hi, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *JobsNoDelimQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("JobsNoDelimQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *JobsNoDelimQuery) Desc() *JobsNoDelimQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *JobsNoDelimQuery) Limit(n int32) *JobsNoDelimQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *JobsNoDelimQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *JobsNoDelimQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *JobsNoDelimQuery) ConsistentRead() *JobsNoDelimQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *JobsNoDelimQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "job",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Job, paginating
// internally. Iteration stops after yielding the first error.
func (q *JobsNoDelimQuery) All(ctx context.Context) iter.Seq2[Job, error] {
	if q.err != nil {
		return func(yield func(Job, error) bool) {
			var zero Job
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalJob)
}

// Page returns one page of matching Job items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *JobsNoDelimQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Job, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalJob)
}

// BatchGetJobs loads Jobs by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *BxClient) BatchGetJobs(ctx context.Context, keys []JobKey, opts ...runtime.ReadOpt) ([]Job, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := jobPK(k.Ten)
		if err != nil {
			return nil, err
		}
		sk, err := jobSK(k.Seq, k.Sub)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Job, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalJob(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutJobs writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *BxClient) BatchPutJobs(ctx context.Context, items []Job) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalJob(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutJob returns a TransactWriteItem putting j (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *BxClient) TransactPutJob(j *Job) (types.TransactWriteItem, error) {
	av, err := marshalJob(j)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteJob returns a TransactWriteItem deleting the
// Job identified by the given key fields.
func (c *BxClient) TransactDeleteJob(ten string, seq int64, sub int64) (types.TransactWriteItem, error) {
	pk, err := jobPK(ten)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := jobSK(seq, sub)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
