// Code generated by ddbgen. DO NOT EDIT.

package bounds

import (
	"context"
	"fmt"
	"iter"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// notePK encodes the Note pk ("TEN#{Ten}") attribute.
func notePK(ten string) (string, error) {
	s0, err := runtime.CheckSegment(ten)
	if err != nil {
		return "", fmt.Errorf("Note pk {Ten}: %w", err)
	}
	return "TEN#" + s0, nil
}

// noteSK encodes the Note sk ("JOB#{Seq:pad4}") attribute.
func noteSK(seq int64) (string, error) {
	s0, err := runtime.EncodePad(seq, 4)
	if err != nil {
		return "", fmt.Errorf("Note sk {Seq:pad4}: %w", err)
	}
	return "JOB#" + s0, nil
}

// NoteKey identifies one Note by its key source fields.
type NoteKey struct {
	Ten string
	Seq int64
}

func (Note) isBxItem() {}

// marshalNote marshals n and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalNote(n *Note) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(n)
	if err != nil {
		return nil, fmt.Errorf("marshaling Note: %w", err)
	}
	pk, err := notePK(n.Ten)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := noteSK(n.Seq)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "note"}
	return av, nil
}

func unmarshalNote(av map[string]types.AttributeValue) (*Note, error) {
	var n Note
	if err := attributevalue.UnmarshalMap(av, &n); err != nil {
		return nil, fmt.Errorf("unmarshaling Note: %w", err)
	}
	return &n, nil
}

// GetNote loads the Note identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *BxClient) GetNote(ctx context.Context, ten string, seq int64, opts ...runtime.ReadOpt) (*Note, error) {
	pk, err := notePK(ten)
	if err != nil {
		return nil, err
	}
	sk, err := noteSK(seq)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetNote: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetNote: %w", runtime.ErrNotFound)
	}
	return unmarshalNote(out.Item)
}

// PutNote writes n unconditionally (last writer wins).
func (c *BxClient) PutNote(ctx context.Context, n *Note) error {
	av, err := marshalNote(n)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutNote: %w", err)
	}
	return nil
}

// PutNoteIfNotExists writes n only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *BxClient) PutNoteIfNotExists(ctx context.Context, n *Note) error {
	av, err := marshalNote(n)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutNoteIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutNoteIfNotExists: %w", err)
	}
	return nil
}

// DeleteNote deletes the Note identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *BxClient) DeleteNote(ctx context.Context, ten string, seq int64, opts ...runtime.DeleteOpt) error {
	pk, err := notePK(ten)
	if err != nil {
		return err
	}
	sk, err := noteSK(seq)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteNote: Note declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteNote: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteNote: %w", err)
	}
	return nil
}

// NoteUpdate is a typed update builder for Note. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type NoteUpdate struct {
	c    *BxClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateNote starts a typed update of the Note identified by
// the given key fields.
func (c *BxClient) UpdateNote(ten string, seq int64) *NoteUpdate {
	u := &NoteUpdate{c: c}
	pk, err := notePK(ten)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := noteSK(seq)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Note. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *NoteUpdate) Run(ctx context.Context) (*Note, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("NoteUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("NoteUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("NoteUpdate: %w", err)
	}
	return unmarshalNote(out.Attributes)
}

// NotesByTenQuery is the chainable builder for the NotesByTen access
// pattern. Terminate with All or Page.
type NotesByTenQuery struct {
	c          *BxClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	refined    bool
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// NotesByTen queries pk = "TEN#{Ten}", sk begins "JOB#" on the main index.
func (c *BxClient) NotesByTen(ten string) *NotesByTenQuery {
	q := &NotesByTenQuery{c: c}
	pk, err := notePK(ten)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	q.skPrefix = "JOB#"
	q.cond = runtime.SKBegins(q.skPrefix)
	return q
}

// SeqAfter restricts results to items with Seq strictly
// after val, at the pad4 encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *NotesByTenQuery) SeqAfter(val int64) *NotesByTenQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// SeqBefore restricts results to items with Seq strictly
// before val, at the pad4 encoding's granularity.
func (q *NotesByTenQuery) SeqBefore(val int64) *NotesByTenQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodePad(val, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredPad(val, 4)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// SeqBetween restricts results to items with Seq between lo
// and hi inclusive.
func (q *NotesByTenQuery) SeqBetween(lo, hi int64) *NotesByTenQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodePad(lo, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodePad(hi, 4)
	if err != nil {
		q.err = fmt.Errorf("SeqBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *NotesByTenQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("NotesByTenQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *NotesByTenQuery) Desc() *NotesByTenQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *NotesByTenQuery) Limit(n int32) *NotesByTenQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *NotesByTenQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *NotesByTenQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *NotesByTenQuery) ConsistentRead() *NotesByTenQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *NotesByTenQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "note",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Note, paginating
// internally. Iteration stops after yielding the first error.
func (q *NotesByTenQuery) All(ctx context.Context) iter.Seq2[Note, error] {
	if q.err != nil {
		return func(yield func(Note, error) bool) {
			var zero Note
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalNote)
}

// Page returns one page of matching Note items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *NotesByTenQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Note, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalNote)
}

// BatchGetNotes loads Notes by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *BxClient) BatchGetNotes(ctx context.Context, keys []NoteKey, opts ...runtime.ReadOpt) ([]Note, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := notePK(k.Ten)
		if err != nil {
			return nil, err
		}
		sk, err := noteSK(k.Seq)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Note, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalNote(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutNotes writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *BxClient) BatchPutNotes(ctx context.Context, items []Note) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalNote(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutNote returns a TransactWriteItem putting n (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *BxClient) TransactPutNote(n *Note) (types.TransactWriteItem, error) {
	av, err := marshalNote(n)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteNote returns a TransactWriteItem deleting the
// Note identified by the given key fields.
func (c *BxClient) TransactDeleteNote(ten string, seq int64) (types.TransactWriteItem, error) {
	pk, err := notePK(ten)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := noteSK(seq)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
