// Code generated by ddbgen. DO NOT EDIT.

package minimal

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// CfgClient is a typed client for the single-table design on table
// "cfg".
type CfgClient struct {
	ddb   runtime.DynamoDB
	table string
}

// NewCfgClient returns a client bound to the given table name. ddb is
// usually *dynamodb.Client; any implementation of the runtime.DynamoDB
// subset works, so tests can substitute a mock and middleware can wrap.
func NewCfgClient(ddb runtime.DynamoDB, table string) *CfgClient {
	return &CfgClient{ddb: ddb, table: table}
}

// DynamoDB returns the underlying client, the escape hatch for operations
// the generated surface does not cover.
func (c *CfgClient) DynamoDB() runtime.DynamoDB { return c.ddb }

// TableName returns the physical table name the client is bound to.
func (c *CfgClient) TableName() string { return c.table }

// CfgItem is the sealed union of entity types stored in table
// "cfg": Config.
type CfgItem interface{ isCfgItem() }

// TransactWrite executes the given write items in one atomic transaction
// (thin passthrough over DynamoDB TransactWriteItems; at most 100 items).
// Build items with the TransactPut/TransactDelete helpers. A failed
// condition inside the transaction surfaces as runtime.ErrConditionFailed.
func (c *CfgClient) TransactWrite(ctx context.Context, items ...types.TransactWriteItem) error {
	if len(items) == 0 {
		return nil
	}
	_, err := c.ddb.TransactWriteItems(ctx, &dynamodb.TransactWriteItemsInput{
		TransactItems: items,
	})
	if err != nil {
		if runtime.IsTransactionConditionFailed(err) {
			// Both errors stay in the chain: match the sentinel with
			// errors.Is, or errors.As the SDK exception for its
			// CancellationReasons.
			return fmt.Errorf("TransactWrite: %w: %w", runtime.ErrConditionFailed, err)
		}
		return fmt.Errorf("TransactWrite: %w", err)
	}
	return nil
}
