// Code generated by ddbgen. DO NOT EDIT.

package minimal

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

// CfgClient is a typed client for the single-table design on table
// "cfg".
type CfgClient struct {
	ddb   *dynamodb.Client
	table string
}

// NewCfgClient returns a client bound to the given table name.
func NewCfgClient(ddb *dynamodb.Client, table string) *CfgClient {
	return &CfgClient{ddb: ddb, table: table}
}

// CfgItem is the sealed union of entity types stored in table
// "cfg": Config.
type CfgItem interface{ isCfgItem() }
