// Code generated by ddbgen. DO NOT EDIT.

package minimal

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// configPK encodes the Config pk ("CONFIG#{Name}") attribute.
func configPK(name string) (string, error) {
	s0, err := runtime.CheckSegment(name)
	if err != nil {
		return "", fmt.Errorf("Config pk {Name}: %w", err)
	}
	return "CONFIG#" + s0, nil
}

// ConfigKey identifies one Config by its key source fields.
type ConfigKey struct {
	Name string
}

func (Config) isCfgItem() {}

// marshalConfig marshals it and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalConfig(it *Config) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(it)
	if err != nil {
		return nil, fmt.Errorf("marshaling Config: %w", err)
	}
	pk, err := configPK(it.Name)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	av["_et"] = &types.AttributeValueMemberS{Value: "config"}
	return av, nil
}

func unmarshalConfig(av map[string]types.AttributeValue) (*Config, error) {
	var it Config
	if err := attributevalue.UnmarshalMap(av, &it); err != nil {
		return nil, fmt.Errorf("unmarshaling Config: %w", err)
	}
	return &it, nil
}

// GetConfig loads the Config identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists.
func (c *CfgClient) GetConfig(ctx context.Context, name string) (*Config, error) {
	pk, err := configPK(name)
	if err != nil {
		return nil, err
	}
	out, err := c.ddb.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("GetConfig: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetConfig: %w", runtime.ErrNotFound)
	}
	return unmarshalConfig(out.Item)
}

// PutConfig writes it unconditionally (last writer wins).
func (c *CfgClient) PutConfig(ctx context.Context, it *Config) error {
	av, err := marshalConfig(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutConfig: %w", err)
	}
	return nil
}

// PutConfigIfNotExists writes it only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *CfgClient) PutConfigIfNotExists(ctx context.Context, it *Config) error {
	av, err := marshalConfig(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutConfigIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutConfigIfNotExists: %w", err)
	}
	return nil
}

// DeleteConfig deletes the Config identified by the given key
// fields. Deleting a missing item is not an error.
func (c *CfgClient) DeleteConfig(ctx context.Context, name string) error {
	pk, err := configPK(name)
	if err != nil {
		return err
	}
	if _, err := c.ddb.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
		},
	}); err != nil {
		return fmt.Errorf("DeleteConfig: %w", err)
	}
	return nil
}

// ConfigUpdate is a typed update builder for Config. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type ConfigUpdate struct {
	c    *CfgClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateConfig starts a typed update of the Config identified by
// the given key fields.
func (c *CfgClient) UpdateConfig(name string) *ConfigUpdate {
	u := &ConfigUpdate{c: c}
	pk, err := configPK(name)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
	}
	return u
}

// SetValue sets the Value attribute.
func (u *ConfigUpdate) SetValue(value string) *ConfigUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(value)
	if err != nil {
		u.err = fmt.Errorf("SetValue: %w", err)
		return u
	}
	u.expr.Set("value", av)
	return u
}

// RemoveValue removes the Value attribute from the item.
func (u *ConfigUpdate) RemoveValue() *ConfigUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("value")
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Config. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *ConfigUpdate) Run(ctx context.Context) (*Config, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("ConfigUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("ConfigUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("ConfigUpdate: %w", err)
	}
	return unmarshalConfig(out.Attributes)
}
