// Code generated by ddbgen. DO NOT EDIT.

package minimal

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// configPK encodes the Config pk ("CONFIG#{Name}") attribute.
func configPK(name string) (string, error) {
	s0, err := runtime.CheckSegment(name)
	if err != nil {
		return "", fmt.Errorf("Config pk {Name}: %w", err)
	}
	return "CONFIG#" + s0, nil
}

// ConfigKey identifies one Config by its key source fields.
type ConfigKey struct {
	Name string
}

func (Config) isCfgItem() {}

// marshalConfig marshals it and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalConfig(it *Config) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(it)
	if err != nil {
		return nil, fmt.Errorf("marshaling Config: %w", err)
	}
	pk, err := configPK(it.Name)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	av["_et"] = &types.AttributeValueMemberS{Value: "config"}
	return av, nil
}

func unmarshalConfig(av map[string]types.AttributeValue) (*Config, error) {
	var it Config
	if err := attributevalue.UnmarshalMap(av, &it); err != nil {
		return nil, fmt.Errorf("unmarshaling Config: %w", err)
	}
	return &it, nil
}

// GetConfig loads the Config identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *CfgClient) GetConfig(ctx context.Context, name string, opts ...runtime.ReadOpt) (*Config, error) {
	pk, err := configPK(name)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetConfig: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetConfig: %w", runtime.ErrNotFound)
	}
	return unmarshalConfig(out.Item)
}

// PutConfig writes it unconditionally (last writer wins).
func (c *CfgClient) PutConfig(ctx context.Context, it *Config) error {
	av, err := marshalConfig(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}); err != nil {
		return fmt.Errorf("PutConfig: %w", err)
	}
	return nil
}

// PutConfigIfNotExists writes it only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *CfgClient) PutConfigIfNotExists(ctx context.Context, it *Config) error {
	av, err := marshalConfig(it)
	if err != nil {
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
		},
	}); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutConfigIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutConfigIfNotExists: %w", err)
	}
	return nil
}

// DeleteConfig deletes the Config identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist().
func (c *CfgClient) DeleteConfig(ctx context.Context, name string, opts ...runtime.DeleteOpt) error {
	pk, err := configPK(name)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	if do.ExpectVersion != nil {
		return fmt.Errorf("DeleteConfig: Config declares no version field; WithExpectVersion is not applicable")
	}
	switch {
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("DeleteConfig: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteConfig: %w", err)
	}
	return nil
}

// ConfigUpdate is a typed update builder for Config. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type ConfigUpdate struct {
	c    *CfgClient
	key  map[string]types.AttributeValue
	expr runtime.UpdateExpr
	err  error
}

// UpdateConfig starts a typed update of the Config identified by
// the given key fields.
func (c *CfgClient) UpdateConfig(name string) *ConfigUpdate {
	u := &ConfigUpdate{c: c}
	pk, err := configPK(name)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
	}
	return u
}

// SetValue sets the Value attribute.
func (u *ConfigUpdate) SetValue(value string) *ConfigUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(value)
	if err != nil {
		u.err = fmt.Errorf("SetValue: %w", err)
		return u
	}
	u.expr.Set("value", av)
	return u
}

// RemoveValue removes the Value attribute from the item.
func (u *ConfigUpdate) RemoveValue() *ConfigUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("value")
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Config. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *ConfigUpdate) Run(ctx context.Context) (*Config, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("ConfigUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			return nil, fmt.Errorf("ConfigUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("ConfigUpdate: %w", err)
	}
	return unmarshalConfig(out.Attributes)
}

// BatchGetConfigs loads Configs by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *CfgClient) BatchGetConfigs(ctx context.Context, keys []ConfigKey, opts ...runtime.ReadOpt) ([]Config, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := configPK(k.Name)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Config, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalConfig(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutConfigs writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes.
func (c *CfgClient) BatchPutConfigs(ctx context.Context, items []Config) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalConfig(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutConfig returns a TransactWriteItem putting it (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *CfgClient) TransactPutConfig(it *Config) (types.TransactWriteItem, error) {
	av, err := marshalConfig(it)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteConfig returns a TransactWriteItem deleting the
// Config identified by the given key fields.
func (c *CfgClient) TransactDeleteConfig(name string) (types.TransactWriteItem, error) {
	pk, err := configPK(name)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
			},
		},
	}, nil
}
