package emit

import (
	"fmt"
	"strings"

	"github.com/ResonanceCache/ddbgen/internal/codegen"
	"github.com/ResonanceCache/ddbgen/internal/schema"
)

// AccessPatterns renders ACCESS_PATTERNS.md for all tables in the schema:
// the single-table design document that is regenerated from the same parse
// as the code, so it is always current.
func AccessPatterns(s *schema.Schema) ([]byte, error) {
	var b strings.Builder
	b.WriteString("# Access patterns\n\n")
	b.WriteString("<!-- Generated by ddbgen. DO NOT EDIT. -->\n\n")
	b.WriteString("This document is emitted by `ddbgen docs` from the same schema parse\n")
	b.WriteString("that generates the client and the infrastructure, so it is always\n")
	b.WriteString("current: if a pattern changes, this file changes in the same commit.\n")
	for _, t := range s.Tables {
		rows, err := codegen.DocRows(t)
		if err != nil {
			return nil, err
		}
		fmt.Fprintf(&b, "\n## Table `%s`\n\n", t.Name)
		if len(rows) == 0 {
			b.WriteString("No access patterns declared.\n")
			continue
		}
		b.WriteString("| Pattern | Index | Key condition | Returns | Generated method |\n")
		b.WriteString("|---|---|---|---|---|\n")
		for _, r := range rows {
			fmt.Fprintf(&b, "| %s | %s | %s | %s | `%s` |\n",
				r.Pattern, r.Index, escapePipes(r.KeyCondition), escapePipes(r.Returns), r.Method)
		}
	}
	return []byte(b.String()), nil
}

func escapePipes(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
