// Code generated by ddbgen. DO NOT EDIT.

package ecommerce

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
)

// AppClient is a typed client for the single-table design on table
// "app".
type AppClient struct {
	ddb   *dynamodb.Client
	table string
}

// NewAppClient returns a client bound to the given table name.
func NewAppClient(ddb *dynamodb.Client, table string) *AppClient {
	return &AppClient{ddb: ddb, table: table}
}

// AppItem is the sealed union of entity types stored in table
// "app": Order, Payment.
type AppItem interface{ isAppItem() }
