// Code generated by ddbgen. DO NOT EDIT.

package ecommerce

import (
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// orderPK encodes the Order pk ("TENANT#{TenantID}") attribute.
func orderPK(tenantID string) (string, error) {
	s0, err := runtime.CheckSegment(tenantID)
	if err != nil {
		return "", fmt.Errorf("Order pk {TenantID}: %w", err)
	}
	return "TENANT#" + s0, nil
}

// orderSK encodes the Order sk ("ORDER#{CreatedAt:rfc3339}#{OrderID}") attribute.
func orderSK(createdAt time.Time, orderID string) (string, error) {
	s0, err := runtime.EncodeRFC3339(createdAt)
	if err != nil {
		return "", fmt.Errorf("Order sk {CreatedAt:rfc3339}: %w", err)
	}
	s1, err := runtime.CheckSegment(orderID)
	if err != nil {
		return "", fmt.Errorf("Order sk {OrderID}: %w", err)
	}
	return "ORDER#" + s0 + "#" + s1, nil
}

// orderGSI1PK encodes the Order gsi1pk ("STATUS#{Status:upper}") attribute.
func orderGSI1PK(status string) (string, error) {
	s0, err := runtime.CheckSegment(strings.ToUpper(status))
	if err != nil {
		return "", fmt.Errorf("Order gsi1pk {Status:upper}: %w", err)
	}
	return "STATUS#" + s0, nil
}

// orderGSI1SK encodes the Order gsi1sk ("{UpdatedAt:epoch}") attribute.
func orderGSI1SK(updatedAt time.Time) (string, error) {
	s0, err := runtime.EncodeEpochTime(updatedAt)
	if err != nil {
		return "", fmt.Errorf("Order gsi1sk {UpdatedAt:epoch}: %w", err)
	}
	return s0, nil
}

// OrderKey identifies one Order by its key source fields.
type OrderKey struct {
	TenantID  string
	CreatedAt time.Time
	OrderID   string
}

func (Order) isAppItem() {}

// marshalOrder marshals o and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalOrder(o *Order) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(o)
	if err != nil {
		return nil, fmt.Errorf("marshaling Order: %w", err)
	}
	pk, err := orderPK(o.TenantID)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := orderSK(o.CreatedAt, o.OrderID)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	gsi1pk, err := orderGSI1PK(o.Status)
	if err != nil {
		return nil, err
	}
	av["gsi1pk"] = &types.AttributeValueMemberS{Value: gsi1pk}
	gsi1sk, err := orderGSI1SK(o.UpdatedAt)
	if err != nil {
		return nil, err
	}
	av["gsi1sk"] = &types.AttributeValueMemberS{Value: gsi1sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "order"}
	return av, nil
}

func unmarshalOrder(av map[string]types.AttributeValue) (*Order, error) {
	var o Order
	if err := attributevalue.UnmarshalMap(av, &o); err != nil {
		return nil, fmt.Errorf("unmarshaling Order: %w", err)
	}
	return &o, nil
}

// GetOrder loads the Order identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists.
func (c *AppClient) GetOrder(ctx context.Context, tenantID string, createdAt time.Time, orderID string) (*Order, error) {
	pk, err := orderPK(tenantID)
	if err != nil {
		return nil, err
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		return nil, err
	}
	out, err := c.ddb.GetItem(ctx, &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	})
	if err != nil {
		return nil, fmt.Errorf("GetOrder: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetOrder: %w", runtime.ErrNotFound)
	}
	return unmarshalOrder(out.Item)
}

// PutOrder writes o with optimistic locking on Ver:
// when o.Ver is zero the item must not exist yet; otherwise the stored
// version must still equal it. The written item carries Ver+1, and
// o.Ver is advanced in place on success. A lost race returns
// runtime.ErrVersionConflict.
func (c *AppClient) PutOrder(ctx context.Context, o *Order) error {
	expected := o.Ver
	o.Ver = expected + 1
	av, err := marshalOrder(o)
	if err != nil {
		o.Ver = expected
		return err
	}
	input := &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}
	if expected == 0 {
		input.ConditionExpression = aws.String("attribute_not_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	} else {
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": "v"}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt(expected, 10)},
		}
	}
	if _, err := c.ddb.PutItem(ctx, input); err != nil {
		o.Ver = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutOrder: %w", runtime.ErrVersionConflict)
		}
		return fmt.Errorf("PutOrder: %w", err)
	}
	return nil
}

// PutOrderIfNotExists writes o only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *AppClient) PutOrderIfNotExists(ctx context.Context, o *Order) error {
	expected := o.Ver
	if expected == 0 {
		o.Ver = 1
	}
	av, err := marshalOrder(o)
	if err != nil {
		o.Ver = expected
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		o.Ver = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutOrderIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutOrderIfNotExists: %w", err)
	}
	return nil
}

// DeleteOrder deletes the Order identified by the given key
// fields. Deleting a missing item is not an error.
func (c *AppClient) DeleteOrder(ctx context.Context, tenantID string, createdAt time.Time, orderID string) error {
	pk, err := orderPK(tenantID)
	if err != nil {
		return err
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		return err
	}
	if _, err := c.ddb.DeleteItem(ctx, &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}); err != nil {
		return fmt.Errorf("DeleteOrder: %w", err)
	}
	return nil
}

// OrderUpdate is a typed update builder for Order. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type OrderUpdate struct {
	c             *AppClient
	key           map[string]types.AttributeValue
	expr          runtime.UpdateExpr
	expectVersion *int64
	err           error
}

// UpdateOrder starts a typed update of the Order identified by
// the given key fields.
func (c *AppClient) UpdateOrder(tenantID string, createdAt time.Time, orderID string) *OrderUpdate {
	u := &OrderUpdate{c: c}
	pk, err := orderPK(tenantID)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// SetStatus sets the Status attribute and recomputes the
// synthesized gsi1pk key attribute (GSI1 stays in sync).
func (u *OrderUpdate) SetStatus(status string) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(status)
	if err != nil {
		u.err = fmt.Errorf("SetStatus: %w", err)
		return u
	}
	u.expr.Set("status", av)
	gsi1pk, err := orderGSI1PK(status)
	if err != nil {
		u.err = fmt.Errorf("SetStatus: %w", err)
		return u
	}
	u.expr.Set("gsi1pk", &types.AttributeValueMemberS{Value: gsi1pk})
	return u
}

// SetTotal sets the Total attribute.
func (u *OrderUpdate) SetTotal(total int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(total)
	if err != nil {
		u.err = fmt.Errorf("SetTotal: %w", err)
		return u
	}
	u.expr.Set("total", av)
	return u
}

// AddTotal atomically adds delta to the Total attribute.
func (u *OrderUpdate) AddTotal(delta int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Add("total", &types.AttributeValueMemberN{Value: strconv.FormatInt(delta, 10)})
	return u
}

// RemoveTotal removes the Total attribute from the item.
func (u *OrderUpdate) RemoveTotal() *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("total")
	return u
}

// SetUpdatedAt sets the UpdatedAt attribute and recomputes the
// synthesized gsi1sk key attribute (GSI1 stays in sync).
func (u *OrderUpdate) SetUpdatedAt(updatedAt time.Time) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(updatedAt)
	if err != nil {
		u.err = fmt.Errorf("SetUpdatedAt: %w", err)
		return u
	}
	u.expr.Set("updated_at", av)
	gsi1sk, err := orderGSI1SK(updatedAt)
	if err != nil {
		u.err = fmt.Errorf("SetUpdatedAt: %w", err)
		return u
	}
	u.expr.Set("gsi1sk", &types.AttributeValueMemberS{Value: gsi1sk})
	return u
}

// SetExpiresAt sets the ExpiresAt attribute.
func (u *OrderUpdate) SetExpiresAt(expiresAt int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(expiresAt)
	if err != nil {
		u.err = fmt.Errorf("SetExpiresAt: %w", err)
		return u
	}
	u.expr.Set("exp", av)
	return u
}

// AddExpiresAt atomically adds delta to the ExpiresAt attribute.
func (u *OrderUpdate) AddExpiresAt(delta int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Add("exp", &types.AttributeValueMemberN{Value: strconv.FormatInt(delta, 10)})
	return u
}

// RemoveExpiresAt removes the ExpiresAt attribute from the item.
func (u *OrderUpdate) RemoveExpiresAt() *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("exp")
	return u
}

// ExpectVersion conditions the update on the stored Ver still
// being version, so Run returns runtime.ErrVersionConflict on a lost race.
// Without it the update increments Ver unconditionally.
func (u *OrderUpdate) ExpectVersion(version int64) *OrderUpdate {
	u.expectVersion = &version
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Order. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *OrderUpdate) Run(ctx context.Context) (*Order, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("OrderUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	u.expr.IncrementVersion("v")
	if u.expectVersion != nil {
		cond += " AND #p1 = :p1"
		names["#p1"] = "v"
		values[":p1"] = &types.AttributeValueMemberN{Value: strconv.FormatInt(*u.expectVersion, 10)}
	}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			if u.expectVersion != nil {
				return nil, fmt.Errorf("OrderUpdate: %w", runtime.ErrVersionConflict)
			}
			return nil, fmt.Errorf("OrderUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("OrderUpdate: %w", err)
	}
	return unmarshalOrder(out.Attributes)
}
