// Code generated by ddbgen. DO NOT EDIT.

package ecommerce

import (
	"context"
	"fmt"
	"iter"
	"strconv"
	"strings"
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/feature/dynamodb/attributevalue"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"

	"github.com/ResonanceCache/ddbgen/runtime"
)

// orderPK encodes the Order pk ("TENANT#{TenantID}") attribute.
func orderPK(tenantID string) (string, error) {
	s0, err := runtime.CheckSegment(tenantID)
	if err != nil {
		return "", fmt.Errorf("Order pk {TenantID}: %w", err)
	}
	return "TENANT#" + s0, nil
}

// orderSK encodes the Order sk ("ORDER#{CreatedAt:rfc3339}#{OrderID}") attribute.
func orderSK(createdAt time.Time, orderID string) (string, error) {
	s0, err := runtime.EncodeRFC3339(createdAt)
	if err != nil {
		return "", fmt.Errorf("Order sk {CreatedAt:rfc3339}: %w", err)
	}
	s1, err := runtime.CheckSegment(orderID)
	if err != nil {
		return "", fmt.Errorf("Order sk {OrderID}: %w", err)
	}
	return "ORDER#" + s0 + "#" + s1, nil
}

// orderGSI1PK encodes the Order gsi1pk ("STATUS#{Status:upper}") attribute.
func orderGSI1PK(status string) (string, error) {
	s0, err := runtime.CheckSegment(strings.ToUpper(status))
	if err != nil {
		return "", fmt.Errorf("Order gsi1pk {Status:upper}: %w", err)
	}
	return "STATUS#" + s0, nil
}

// orderGSI1SK encodes the Order gsi1sk ("{UpdatedAt:epoch}") attribute.
func orderGSI1SK(updatedAt time.Time) (string, error) {
	s0, err := runtime.EncodeEpochTime(updatedAt)
	if err != nil {
		return "", fmt.Errorf("Order gsi1sk {UpdatedAt:epoch}: %w", err)
	}
	return s0, nil
}

// OrderKey identifies one Order by its key source fields.
type OrderKey struct {
	TenantID  string
	CreatedAt time.Time
	OrderID   string
}

func (Order) isAppItem() {}

// marshalOrder marshals o and synthesizes the physical key
// attributes and the entity-type attribute from source fields, so index
// keys can never drift from the data.
func marshalOrder(o *Order) (map[string]types.AttributeValue, error) {
	av, err := attributevalue.MarshalMap(o)
	if err != nil {
		return nil, fmt.Errorf("marshaling Order: %w", err)
	}
	pk, err := orderPK(o.TenantID)
	if err != nil {
		return nil, err
	}
	av["pk"] = &types.AttributeValueMemberS{Value: pk}
	sk, err := orderSK(o.CreatedAt, o.OrderID)
	if err != nil {
		return nil, err
	}
	av["sk"] = &types.AttributeValueMemberS{Value: sk}
	gsi1pk, err := orderGSI1PK(o.Status)
	if err != nil {
		return nil, err
	}
	av["gsi1pk"] = &types.AttributeValueMemberS{Value: gsi1pk}
	gsi1sk, err := orderGSI1SK(o.UpdatedAt)
	if err != nil {
		return nil, err
	}
	av["gsi1sk"] = &types.AttributeValueMemberS{Value: gsi1sk}
	av["_et"] = &types.AttributeValueMemberS{Value: "order"}
	return av, nil
}

func unmarshalOrder(av map[string]types.AttributeValue) (*Order, error) {
	var o Order
	if err := attributevalue.UnmarshalMap(av, &o); err != nil {
		return nil, fmt.Errorf("unmarshaling Order: %w", err)
	}
	return &o, nil
}

// GetOrder loads the Order identified by the given key fields.
// It returns runtime.ErrNotFound when no such item exists. Pass
// runtime.WithConsistentRead() for a strongly consistent read.
func (c *AppClient) GetOrder(ctx context.Context, tenantID string, createdAt time.Time, orderID string, opts ...runtime.ReadOpt) (*Order, error) {
	pk, err := orderPK(tenantID)
	if err != nil {
		return nil, err
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		return nil, err
	}
	input := &dynamodb.GetItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	if runtime.ResolveReadOpts(opts).ConsistentRead {
		input.ConsistentRead = aws.Bool(true)
	}
	out, err := c.ddb.GetItem(ctx, input)
	if err != nil {
		return nil, fmt.Errorf("GetOrder: %w", err)
	}
	if out.Item == nil {
		return nil, fmt.Errorf("GetOrder: %w", runtime.ErrNotFound)
	}
	return unmarshalOrder(out.Item)
}

// PutOrder writes o with optimistic locking on Ver:
// when o.Ver is zero the item must not exist yet; otherwise the stored
// version must still equal it. The written item carries Ver+1, and
// o.Ver is advanced in place on success. A lost race returns
// runtime.ErrVersionConflict.
func (c *AppClient) PutOrder(ctx context.Context, o *Order) error {
	expected := o.Ver
	o.Ver = expected + 1
	av, err := marshalOrder(o)
	if err != nil {
		o.Ver = expected
		return err
	}
	input := &dynamodb.PutItemInput{
		TableName: aws.String(c.table),
		Item:      av,
	}
	if expected == 0 {
		input.ConditionExpression = aws.String("attribute_not_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	} else {
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": "v"}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt(expected, 10)},
		}
	}
	if _, err := c.ddb.PutItem(ctx, input); err != nil {
		o.Ver = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutOrder: %w", runtime.ErrVersionConflict)
		}
		return fmt.Errorf("PutOrder: %w", err)
	}
	return nil
}

// PutOrderIfNotExists writes o only when no item with the same key
// exists, returning runtime.ErrConditionFailed otherwise.
func (c *AppClient) PutOrderIfNotExists(ctx context.Context, o *Order) error {
	expected := o.Ver
	if expected == 0 {
		o.Ver = 1
	}
	av, err := marshalOrder(o)
	if err != nil {
		o.Ver = expected
		return err
	}
	if _, err := c.ddb.PutItem(ctx, &dynamodb.PutItemInput{
		TableName:           aws.String(c.table),
		Item:                av,
		ConditionExpression: aws.String("attribute_not_exists(#p0) AND attribute_not_exists(#p1)"),
		ExpressionAttributeNames: map[string]string{
			"#p0": "pk",
			"#p1": "sk",
		},
	}); err != nil {
		o.Ver = expected
		if runtime.IsConditionalCheckFailed(err) {
			return fmt.Errorf("PutOrderIfNotExists: %w", runtime.ErrConditionFailed)
		}
		return fmt.Errorf("PutOrderIfNotExists: %w", err)
	}
	return nil
}

// DeleteOrder deletes the Order identified by the given key
// fields. By default deleting a missing item is not an error; condition
// the delete with runtime.WithMustExist() or
// runtime.WithExpectVersion(v).
func (c *AppClient) DeleteOrder(ctx context.Context, tenantID string, createdAt time.Time, orderID string, opts ...runtime.DeleteOpt) error {
	pk, err := orderPK(tenantID)
	if err != nil {
		return err
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		return err
	}
	input := &dynamodb.DeleteItemInput{
		TableName: aws.String(c.table),
		Key: map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		},
	}
	do := runtime.ResolveDeleteOpts(opts)
	switch {
	case do.ExpectVersion != nil:
		input.ConditionExpression = aws.String("#v0 = :v0")
		input.ExpressionAttributeNames = map[string]string{"#v0": "v"}
		input.ExpressionAttributeValues = map[string]types.AttributeValue{
			":v0": &types.AttributeValueMemberN{Value: strconv.FormatInt(*do.ExpectVersion, 10)},
		}
	case do.MustExist:
		input.ConditionExpression = aws.String("attribute_exists(#p0)")
		input.ExpressionAttributeNames = map[string]string{"#p0": "pk"}
	}
	if _, err := c.ddb.DeleteItem(ctx, input); err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			if do.ExpectVersion != nil {
				return fmt.Errorf("DeleteOrder: %w", runtime.ErrVersionConflict)
			}
			return fmt.Errorf("DeleteOrder: %w", runtime.ErrNotFound)
		}
		return fmt.Errorf("DeleteOrder: %w", err)
	}
	return nil
}

// OrderUpdate is a typed update builder for Order. Chain
// setters, then call Run. Key source fields are fixed by the constructor;
// synthesized index keys are recomputed automatically by the setters of
// their source fields.
type OrderUpdate struct {
	c             *AppClient
	key           map[string]types.AttributeValue
	expr          runtime.UpdateExpr
	expectVersion *int64
	err           error
}

// UpdateOrder starts a typed update of the Order identified by
// the given key fields.
func (c *AppClient) UpdateOrder(tenantID string, createdAt time.Time, orderID string) *OrderUpdate {
	u := &OrderUpdate{c: c}
	pk, err := orderPK(tenantID)
	if err != nil {
		u.err = err
		return u
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		u.err = err
		return u
	}
	u.key = map[string]types.AttributeValue{
		"pk": &types.AttributeValueMemberS{Value: pk},
		"sk": &types.AttributeValueMemberS{Value: sk},
	}
	return u
}

// SetStatus sets the Status attribute and recomputes the
// synthesized gsi1pk key attribute (GSI1 stays in sync).
func (u *OrderUpdate) SetStatus(status string) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(status)
	if err != nil {
		u.err = fmt.Errorf("SetStatus: %w", err)
		return u
	}
	u.expr.Set("status", av)
	gsi1pk, err := orderGSI1PK(status)
	if err != nil {
		u.err = fmt.Errorf("SetStatus: %w", err)
		return u
	}
	u.expr.Set("gsi1pk", &types.AttributeValueMemberS{Value: gsi1pk})
	return u
}

// SetTotal sets the Total attribute.
func (u *OrderUpdate) SetTotal(total int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(total)
	if err != nil {
		u.err = fmt.Errorf("SetTotal: %w", err)
		return u
	}
	u.expr.Set("total", av)
	return u
}

// AddTotal atomically adds delta to the Total attribute.
func (u *OrderUpdate) AddTotal(delta int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Add("total", &types.AttributeValueMemberN{Value: strconv.FormatInt(delta, 10)})
	return u
}

// RemoveTotal removes the Total attribute from the item.
func (u *OrderUpdate) RemoveTotal() *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("total")
	return u
}

// SetUpdatedAt sets the UpdatedAt attribute and recomputes the
// synthesized gsi1sk key attribute (GSI1 stays in sync).
func (u *OrderUpdate) SetUpdatedAt(updatedAt time.Time) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(updatedAt)
	if err != nil {
		u.err = fmt.Errorf("SetUpdatedAt: %w", err)
		return u
	}
	u.expr.Set("updated_at", av)
	gsi1sk, err := orderGSI1SK(updatedAt)
	if err != nil {
		u.err = fmt.Errorf("SetUpdatedAt: %w", err)
		return u
	}
	u.expr.Set("gsi1sk", &types.AttributeValueMemberS{Value: gsi1sk})
	return u
}

// SetExpiresAt sets the ExpiresAt attribute.
func (u *OrderUpdate) SetExpiresAt(expiresAt int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	av, err := attributevalue.Marshal(expiresAt)
	if err != nil {
		u.err = fmt.Errorf("SetExpiresAt: %w", err)
		return u
	}
	u.expr.Set("exp", av)
	return u
}

// AddExpiresAt atomically adds delta to the ExpiresAt attribute.
func (u *OrderUpdate) AddExpiresAt(delta int64) *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Add("exp", &types.AttributeValueMemberN{Value: strconv.FormatInt(delta, 10)})
	return u
}

// RemoveExpiresAt removes the ExpiresAt attribute from the item.
func (u *OrderUpdate) RemoveExpiresAt() *OrderUpdate {
	if u.err != nil {
		return u
	}
	u.expr.Remove("exp")
	return u
}

// ExpectVersion conditions the update on the stored Ver still
// being version, so Run returns runtime.ErrVersionConflict on a lost race.
// Without it the update increments Ver unconditionally.
func (u *OrderUpdate) ExpectVersion(version int64) *OrderUpdate {
	u.expectVersion = &version
	return u
}

// Run executes the update with ReturnValues=ALL_NEW and returns the
// updated Order. The update requires the item to exist; a missing
// item returns runtime.ErrNotFound.
func (u *OrderUpdate) Run(ctx context.Context) (*Order, error) {
	if u.err != nil {
		return nil, u.err
	}
	if u.expr.Empty() {
		return nil, fmt.Errorf("OrderUpdate: no changes; call a setter before Run")
	}
	cond := "attribute_exists(#p0)"
	names := map[string]string{"#p0": "pk"}
	values := map[string]types.AttributeValue{}
	u.expr.IncrementVersion("v")
	if u.expectVersion != nil {
		cond += " AND #p1 = :p1"
		names["#p1"] = "v"
		values[":p1"] = &types.AttributeValueMemberN{Value: strconv.FormatInt(*u.expectVersion, 10)}
	}
	out, err := u.c.ddb.UpdateItem(ctx, &dynamodb.UpdateItemInput{
		TableName:                 aws.String(u.c.table),
		Key:                       u.key,
		UpdateExpression:          aws.String(u.expr.Expression()),
		ConditionExpression:       aws.String(cond),
		ExpressionAttributeNames:  u.expr.Names(names),
		ExpressionAttributeValues: u.expr.Values(values),
		ReturnValues:              types.ReturnValueAllNew,
	})
	if err != nil {
		if runtime.IsConditionalCheckFailed(err) {
			if u.expectVersion != nil {
				return nil, fmt.Errorf("OrderUpdate: %w", runtime.ErrVersionConflict)
			}
			return nil, fmt.Errorf("OrderUpdate: %w", runtime.ErrNotFound)
		}
		return nil, fmt.Errorf("OrderUpdate: %w", err)
	}
	return unmarshalOrder(out.Attributes)
}

// OrdersByStatusQuery is the chainable builder for the OrdersByStatus access
// pattern. Terminate with All or Page.
type OrdersByStatusQuery struct {
	c        *AppClient
	pk       string
	skPrefix string
	cond     runtime.SKCond
	refined  bool
	desc     bool
	limit    int32
	filter   *runtime.Filter
	err      error
}

// OrdersByStatus queries pk = "STATUS#{Status:upper}" on GSI GSI1.
func (c *AppClient) OrdersByStatus(status string) *OrdersByStatusQuery {
	q := &OrdersByStatusQuery{c: c}
	pk, err := orderGSI1PK(status)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	return q
}

// UpdatedAfter restricts results to items with UpdatedAt strictly
// after val, at the epoch encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *OrdersByStatusQuery) UpdatedAfter(val time.Time) *OrdersByStatusQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeEpochTime(val)
	if err != nil {
		q.err = fmt.Errorf("UpdatedAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// UpdatedBefore restricts results to items with UpdatedAt strictly
// before val, at the epoch encoding's granularity.
func (q *OrdersByStatusQuery) UpdatedBefore(val time.Time) *OrdersByStatusQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeEpochTime(val)
	if err != nil {
		q.err = fmt.Errorf("UpdatedBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredEpoch(val.Unix())
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// UpdatedBetween restricts results to items with UpdatedAt between lo
// and hi inclusive.
func (q *OrdersByStatusQuery) UpdatedBetween(lo, hi time.Time) *OrdersByStatusQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodeEpochTime(lo)
	if err != nil {
		q.err = fmt.Errorf("UpdatedBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodeEpochTime(hi)
	if err != nil {
		q.err = fmt.Errorf("UpdatedBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *OrdersByStatusQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("OrdersByStatusQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *OrdersByStatusQuery) Desc() *OrdersByStatusQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *OrdersByStatusQuery) Limit(n int32) *OrdersByStatusQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *OrdersByStatusQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *OrdersByStatusQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *OrdersByStatusQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:   q.c.table,
		Index:   "GSI1",
		PKAttr:  "gsi1pk",
		PKValue: q.pk,
		SKAttr:  "gsi1sk",
		SKCond:  q.cond,
		Desc:    q.desc,
		Limit:   q.limit,
		ETAttr:  "_et",
		ETValue: "order",
		Filter:  q.filter,
	}
}

// All returns an iterator over every matching Order, paginating
// internally. Iteration stops after yielding the first error.
func (q *OrdersByStatusQuery) All(ctx context.Context) iter.Seq2[Order, error] {
	if q.err != nil {
		return func(yield func(Order, error) bool) {
			var zero Order
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalOrder)
}

// Page returns one page of matching Order items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *OrdersByStatusQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Order, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalOrder)
}

// OrdersByTenantQuery is the chainable builder for the OrdersByTenant access
// pattern. Terminate with All or Page.
type OrdersByTenantQuery struct {
	c          *AppClient
	pk         string
	skPrefix   string
	cond       runtime.SKCond
	refined    bool
	desc       bool
	limit      int32
	filter     *runtime.Filter
	consistent bool
	err        error
}

// OrdersByTenant queries pk = "TENANT#{TenantID}", sk begins "ORDER#" on the main index.
func (c *AppClient) OrdersByTenant(tenantID string) *OrdersByTenantQuery {
	q := &OrdersByTenantQuery{c: c}
	pk, err := orderPK(tenantID)
	if err != nil {
		q.err = err
		return q
	}
	q.pk = pk
	q.skPrefix = "ORDER#"
	q.cond = runtime.SKBegins(q.skPrefix)
	return q
}

// CreatedAfter restricts results to items with CreatedAt strictly
// after val, at the rfc3339 encoding's granularity. Bounds stay
// inside the pattern's key scope, so entities sharing the partition can
// never leak into the results.
func (q *OrdersByTenantQuery) CreatedAfter(val time.Time) *OrdersByTenantQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeRFC3339(val)
	if err != nil {
		q.err = fmt.Errorf("CreatedAfter: %w", err)
		return q
	}
	q.cond = runtime.SKAfter(q.skPrefix, q.skPrefix+enc)
	return q
}

// CreatedBefore restricts results to items with CreatedAt strictly
// before val, at the rfc3339 encoding's granularity.
func (q *OrdersByTenantQuery) CreatedBefore(val time.Time) *OrdersByTenantQuery {
	if !q.beginRefine() {
		return q
	}
	enc, err := runtime.EncodeRFC3339(val)
	if err != nil {
		q.err = fmt.Errorf("CreatedBefore: %w", err)
		return q
	}
	pred, ok := runtime.PredRFC3339(val)
	q.cond = runtime.SKBefore(q.skPrefix, q.skPrefix+enc, q.skPrefix+pred, ok)
	return q
}

// CreatedBetween restricts results to items with CreatedAt between lo
// and hi inclusive.
func (q *OrdersByTenantQuery) CreatedBetween(lo, hi time.Time) *OrdersByTenantQuery {
	if !q.beginRefine() {
		return q
	}
	encLo, err := runtime.EncodeRFC3339(lo)
	if err != nil {
		q.err = fmt.Errorf("CreatedBetween: %w", err)
		return q
	}
	encHi, err := runtime.EncodeRFC3339(hi)
	if err != nil {
		q.err = fmt.Errorf("CreatedBetween: %w", err)
		return q
	}
	q.cond = runtime.SKBetween(q.skPrefix+encLo, q.skPrefix+encHi)
	return q
}

// beginRefine reports whether a range refinement may be applied, guarding
// against conflicting refinements.
func (q *OrdersByTenantQuery) beginRefine() bool {
	if q.err != nil {
		return false
	}
	if q.refined {
		q.err = fmt.Errorf("OrdersByTenantQuery: conflicting range refinements")
		return false
	}
	q.refined = true
	return true
}

// Desc returns results in descending key order.
func (q *OrdersByTenantQuery) Desc() *OrdersByTenantQuery {
	q.desc = true
	return q
}

// Limit caps the number of items DynamoDB evaluates per page (it is a page
// size, not a result cap: All still streams every page).
func (q *OrdersByTenantQuery) Limit(n int32) *OrdersByTenantQuery {
	q.limit = n
	return q
}

// Filter applies a raw server-side filter expression on non-key
// attributes — the escape hatch for predicates the key condition cannot
// express. Alias names and value bindings are merged with the ones the
// query already uses; #pk, #sk, #ddbet, :pk, :a, :b, and :ddbet are
// reserved. Filtering runs after the key condition, so filtered-out items
// still consume read capacity.
func (q *OrdersByTenantQuery) Filter(expression string, names map[string]string, values map[string]types.AttributeValue) *OrdersByTenantQuery {
	q.filter = &runtime.Filter{Expression: expression, Names: names, Values: values}
	return q
}

// ConsistentRead makes the query strongly consistent.
func (q *OrdersByTenantQuery) ConsistentRead() *OrdersByTenantQuery {
	q.consistent = true
	return q
}

// spec resolves the query. The entity-type filter makes the typed result
// exact whatever else shares the partition; the key condition keeps the
// scanned range tight.
func (q *OrdersByTenantQuery) spec() runtime.QuerySpec {
	return runtime.QuerySpec{
		Table:      q.c.table,
		PKAttr:     "pk",
		PKValue:    q.pk,
		SKAttr:     "sk",
		SKCond:     q.cond,
		Desc:       q.desc,
		Limit:      q.limit,
		ETAttr:     "_et",
		ETValue:    "order",
		Filter:     q.filter,
		Consistent: q.consistent,
	}
}

// All returns an iterator over every matching Order, paginating
// internally. Iteration stops after yielding the first error.
func (q *OrdersByTenantQuery) All(ctx context.Context) iter.Seq2[Order, error] {
	if q.err != nil {
		return func(yield func(Order, error) bool) {
			var zero Order
			yield(zero, q.err)
		}
	}
	return runtime.QueryAll(ctx, q.c.ddb, q.spec(), unmarshalOrder)
}

// Page returns one page of matching Order items plus the cursor of
// the next page ("" when exhausted). Pass a zero cursor to start.
func (q *OrdersByTenantQuery) Page(ctx context.Context, cursor runtime.Cursor) ([]Order, runtime.Cursor, error) {
	if q.err != nil {
		return nil, "", q.err
	}
	return runtime.QueryPage(ctx, q.c.ddb, q.spec(), cursor, unmarshalOrder)
}

// BatchGetOrders loads Orders by key in chunks of
// 100, retrying unprocessed keys with jittered backoff. Duplicate keys are
// fetched once; missing keys are omitted from the result. On exhausted
// retries the fetched subset is returned along with a
// *runtime.UnprocessedError (errors.Is runtime.ErrUnprocessedRemain)
// carrying the leftover keys. Pass runtime.WithConsistentRead() for
// strongly consistent reads.
func (c *AppClient) BatchGetOrders(ctx context.Context, keys []OrderKey, opts ...runtime.ReadOpt) ([]Order, error) {
	kk := make([]map[string]types.AttributeValue, 0, len(keys))
	for _, k := range keys {
		pk, err := orderPK(k.TenantID)
		if err != nil {
			return nil, err
		}
		sk, err := orderSK(k.CreatedAt, k.OrderID)
		if err != nil {
			return nil, err
		}
		kk = append(kk, map[string]types.AttributeValue{
			"pk": &types.AttributeValueMemberS{Value: pk},
			"sk": &types.AttributeValueMemberS{Value: sk},
		})
	}
	raw, err := runtime.BatchGet(ctx, c.ddb, c.table, kk, runtime.ResolveReadOpts(opts).ConsistentRead)
	out := make([]Order, 0, len(raw))
	for _, av := range raw {
		it, uerr := unmarshalOrder(av)
		if uerr != nil {
			return nil, uerr
		}
		out = append(out, *it)
	}
	return out, err
}

// BatchPutOrders writes items in chunks of 25, retrying
// unprocessed writes with jittered backoff. Two items with the same key
// return runtime.ErrDuplicateKey; on exhausted retries a
// *runtime.UnprocessedError carries the leftover writes. Batch writes bypass
// optimistic locking: items are written with their current Ver as-is.
func (c *AppClient) BatchPutOrders(ctx context.Context, items []Order) error {
	avs := make([]map[string]types.AttributeValue, 0, len(items))
	for i := range items {
		av, err := marshalOrder(&items[i])
		if err != nil {
			return err
		}
		avs = append(avs, av)
	}
	return runtime.BatchWrite(ctx, c.ddb, c.table, avs)
}

// TransactPutOrder returns a TransactWriteItem putting o (with
// synthesized key attributes), for use with TransactWrite. Transactional
// puts are a thin passthrough: no version condition is applied.
func (c *AppClient) TransactPutOrder(o *Order) (types.TransactWriteItem, error) {
	av, err := marshalOrder(o)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Put: &types.Put{TableName: aws.String(c.table), Item: av},
	}, nil
}

// TransactDeleteOrder returns a TransactWriteItem deleting the
// Order identified by the given key fields.
func (c *AppClient) TransactDeleteOrder(tenantID string, createdAt time.Time, orderID string) (types.TransactWriteItem, error) {
	pk, err := orderPK(tenantID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	sk, err := orderSK(createdAt, orderID)
	if err != nil {
		return types.TransactWriteItem{}, err
	}
	return types.TransactWriteItem{
		Delete: &types.Delete{
			TableName: aws.String(c.table),
			Key: map[string]types.AttributeValue{
				"pk": &types.AttributeValueMemberS{Value: pk},
				"sk": &types.AttributeValueMemberS{Value: sk},
			},
		},
	}, nil
}
